export interface Terme {
  slug: string
  terme: string
  definition: string
  explication: string
  exemple: string
  liens: string[]
}

export const GLOSSAIRE: Terme[] = [
  { slug: "acompte", terme: "Acompte", definition: "Paiement partiel versé avant la réalisation complète d'une prestation ou la livraison d'un bien.", explication: "L'acompte engage définitivement les deux parties. Contrairement aux arrhes, il ne peut pas être récupéré en cas d'annulation par le client. Une facture d'acompte doit être émise dès l'encaissement, avec TVA si applicable.", exemple: "Un artisan demande 30 % d'acompte à la signature du devis avant de commencer les travaux.", liens: ["/guide/facture-acompte", "/modele/facture-acompte"] },
  { slug: "arrhes", terme: "Arrhes", definition: "Somme versée à la commande qui permet à chaque partie de se désengager.", explication: "Contrairement à l'acompte, les arrhes permettent l'annulation : le client perd les arrhes, le professionnel les rembourse au double. Sauf mention contraire, les sommes versées sont présumées être des arrhes (article 1590 du Code civil).", exemple: "Un traiteur reçoit 500 € d'arrhes pour une réservation de réception.", liens: ["/guide/devis-obligatoire"] },
  { slug: "avoir", terme: "Avoir (note de crédit)", definition: "Document comptable qui annule ou corrige tout ou partie d'une facture émise.", explication: "L'avoir est obligatoire pour corriger une facture : il est interdit de supprimer ou de modifier une facture déjà émise. L'avoir porte un numéro dans la séquence de facturation et doit référencer la facture d'origine.", exemple: "Un client retourne de la marchandise : le vendeur émet un avoir du montant correspondant.", liens: ["/guide/avoir-facture", "/modele/avoir-annulation"] },
  { slug: "autoliquidation", terme: "Autoliquidation de TVA", definition: "Mécanisme où l'acheteur déclare et déduit lui-même la TVA, au lieu que le vendeur la facture.", explication: "Obligatoire en sous-traitance BTP depuis 2014 (article 283-2 nonies du CGI). Le sous-traitant facture en HT avec la mention « Autoliquidation ». L'entrepreneur principal déclare la TVA sur sa déclaration CA3.", exemple: "Un électricien sous-traitant facture 10 000 € HT sans TVA à l'entreprise générale.", liens: ["/guide/tva-autoliquidation-sous-traitance", "/facturation/electricien"] },
  { slug: "cgv", terme: "Conditions générales de vente (CGV)", definition: "Document contractuel qui détaille les conditions de vente entre un professionnel et ses clients.", explication: "Les CGV sont obligatoires entre professionnels (article L441-1 du Code de commerce). Elles doivent être communiquées à tout acheteur qui en fait la demande. Elles incluent les conditions de paiement, les pénalités de retard et les garanties.", exemple: "Un consultant joint ses CGV à chaque devis, avec ses délais de paiement et ses pénalités.", liens: ["/guide/delai-paiement-facture"] },
  { slug: "devis", terme: "Devis", definition: "Document commercial qui détaille les prestations proposées et leur prix, émis avant la réalisation des travaux.", explication: "Chez un particulier, le devis est obligatoire avant tout dépannage, réparation ou entretien dans le bâtiment, quel qu'en soit le montant, et dans d'autres secteurs (déménagement, services à la personne). Un devis signé vaut engagement contractuel. Il doit mentionner sa durée de validité.", exemple: "Un plombier établit un devis de 2 500 € pour une rénovation de salle de bain.", liens: ["/guide/comment-faire-un-devis", "/guide/devis-obligatoire", "/modele/devis-travaux"] },
  { slug: "e-reporting", terme: "E-reporting", definition: "Obligation de transmettre à l'administration fiscale les données des ventes aux particuliers et des opérations internationales.", explication: "Le e-reporting complète la facturation électronique entre entreprises et suit le même calendrier : depuis le 1er septembre 2026 pour les grandes entreprises et les ETI, à partir du 1er septembre 2027 pour les PME et les micro-entreprises. Les données sont transmises par la plateforme agréée de l'entreprise.", exemple: "Un restaurant transmet périodiquement les données de ses ventes aux particuliers par sa plateforme agréée.", liens: ["/guide/plateforme-agreee", "/guide/facture-electronique-2026"] },
  { slug: "escompte", terme: "Escompte", definition: "Réduction accordée au client en échange d'un paiement anticipé, avant la date d'échéance.", explication: "Les conditions d'escompte doivent figurer sur la facture, même s'il n'est pas accordé (mention « Pas d'escompte pour paiement anticipé »). Si un escompte est proposé, ses conditions doivent être clairement indiquées.", exemple: "Une facture propose 2 % d'escompte si le paiement est effectué sous 10 jours au lieu de 30.", liens: ["/guide/delai-paiement-facture", "/guide/mentions-obligatoires-facture"] },
  { slug: "factur-x", terme: "Factur-X", definition: "Format hybride de facture électronique qui combine un PDF lisible et des données XML structurées (norme EN 16931).", explication: "Factur-X fait partie des formats acceptés par la réforme, avec UBL et CII. Il convient bien aux TPE et PME : le PDF reste lisible par l'humain, tandis que le XML permet le traitement automatique par les logiciels comptables.", exemple: "Le client ouvre le PDF d'une facture Factur-X comme n'importe quel PDF, pendant que son logiciel comptable lit les données du fichier XML joint.", liens: ["/guide/facture-electronique-2026"] },
  { slug: "facture-electronique", terme: "Facture électronique", definition: "Facture émise et reçue dans un format électronique structuré (Factur-X, UBL ou CII), transmise par une plateforme agréée.", explication: "Depuis le 1er septembre 2026, toutes les entreprises assujetties à la TVA doivent pouvoir recevoir des factures électroniques. L'émission est obligatoire depuis la même date pour les grandes entreprises et les ETI, et le sera à partir du 1er septembre 2027 pour les PME et les micro-entreprises. Un simple PDF envoyé par email n'est pas une facture électronique au sens de la réforme.", exemple: "Une entreprise dépose sa facture Factur-X sur sa plateforme agréée, qui la transmet à la plateforme de son client.", liens: ["/guide/plateforme-agreee", "/guide/facture-electronique-2026"] },
  { slug: "fec", terme: "Fichier des écritures comptables (FEC)", definition: "Export standardisé de la comptabilité d'une entreprise, à remettre à l'administration en cas de contrôle fiscal.", explication: "Le FEC est un fichier texte qui contient toutes les écritures comptables de l'exercice. Il doit être présenté à la demande de l'administration fiscale (article L47 A-I du LPF). Son absence est sanctionnée d'une amende de 5 000 €.", exemple: "Une entreprise exporte le FEC de ses ventes depuis son logiciel de facturation et le transmet à son expert-comptable.", liens: ["/guide/conservation-factures"] },
  { slug: "franchise-tva", terme: "Franchise en base de TVA", definition: "Régime fiscal qui dispense les petites entreprises de facturer et de déclarer la TVA.", explication: "La franchise s'applique sous les seuils de chiffre d'affaires de l'article 293 B du CGI : en 2026, 37 500 € pour les services et 85 000 € pour la vente sur l'année précédente, 41 250 € et 93 500 € sur l'année en cours. La mention « TVA non applicable, article 293 B du CGI » doit figurer sur chaque facture.", exemple: "Un auto-entrepreneur sous les seuils facture 1 000 € HT sans ligne de TVA.", liens: ["/guide/facture-auto-entrepreneur", "/facturation/auto-entrepreneur"] },
  { slug: "garantie-decennale", terme: "Garantie décennale", definition: "Assurance obligatoire qui couvre, pendant 10 ans après la réception, les malfaçons compromettant la solidité d'un ouvrage.", explication: "Tout constructeur doit souscrire une assurance décennale (article 1792 du Code civil). Les coordonnées de l'assureur (nom, numéro de contrat, couverture géographique) doivent figurer sur les devis et les factures.", exemple: "Un maçon mentionne sur son devis : « Décennale : [nom de l'assureur], contrat n° 123456, couverture France entière ».", liens: ["/facturation/macon", "/modele/devis-travaux"] },
  { slug: "indemnite-recouvrement", terme: "Indemnité forfaitaire de recouvrement", definition: "Somme de 40 € due de plein droit par le débiteur en cas de retard de paiement entre professionnels.", explication: "Cette indemnité est exigible sans mise en demeure préalable, dès le premier jour de retard (article D441-5 du Code de commerce). Elle doit être mentionnée sur chaque facture. Si les frais réels dépassent 40 €, le créancier peut demander une indemnisation complémentaire.", exemple: "Un fournisseur ajoute 40 € d'indemnité de recouvrement à sa relance pour facture impayée.", liens: ["/guide/delai-paiement-facture", "/modele/lettre-relance-impaye"] },
  { slug: "injonction-payer", terme: "Injonction de payer", definition: "Procédure judiciaire simplifiée qui permet de recouvrer une créance impayée sans audience.", explication: "La requête est déposée auprès du tribunal compétent (tribunal de commerce pour les litiges entre professionnels). Le juge rend une ordonnance en quelques semaines. Le débiteur dispose d'un mois pour faire opposition.", exemple: "Après une mise en demeure restée sans réponse, un artisan dépose une requête en injonction de payer.", liens: ["/guide/facture-impayee"] },
  { slug: "mention-obligatoire", terme: "Mentions obligatoires", definition: "Informations qui doivent figurer sur toute facture, sous peine d'amende (15 € par mention manquante).", explication: "Les mentions incluent : l'identité du vendeur et de l'acheteur, un numéro de facture séquentiel, la date, la désignation des prestations, les prix, la TVA, les conditions de paiement, les pénalités de retard et l'indemnité de recouvrement.", exemple: "Une facture sans numéro SIRET expose le professionnel à une amende de 15 € par facture.", liens: ["/guide/mentions-obligatoires-facture"] },
  { slug: "mise-en-demeure", terme: "Mise en demeure", definition: "Courrier formel (recommandé avec accusé de réception) qui exige le paiement d'une dette, préalable à l'action en justice.", explication: "La mise en demeure doit préciser les références des factures impayées, le montant dû avec les pénalités et le délai accordé (généralement 8 jours). Elle constitue la preuve juridique de la tentative de recouvrement amiable.", exemple: "Un prestataire envoie une mise en demeure en LRAR après deux relances restées sans réponse.", liens: ["/guide/facture-impayee", "/modele/lettre-relance-impaye"] },
  { slug: "note-honoraires", terme: "Note d'honoraires", definition: "Document équivalent à une facture, utilisé par les professions libérales et de santé.", explication: "La note d'honoraires suit les mêmes règles que la facture (mentions obligatoires, numérotation séquentielle). Elle est utilisée par les médecins, ostéopathes, avocats, architectes et autres professions libérales.", exemple: "Un ostéopathe remet une note d'honoraires de 60 € après chaque consultation.", liens: ["/facturation/osteopathe", "/facturation/avocat"] },
  { slug: "numero-facture", terme: "Numéro de facture", definition: "Identifiant unique et séquentiel attribué à chaque facture, obligatoire et inaltérable.", explication: "La numérotation doit être chronologique et continue, sans trou ni doublon. Un préfixe est autorisé (ex : F-2026-001). Il est interdit de supprimer un numéro : en cas d'erreur, il faut émettre un avoir.", exemple: "Les factures d'une entreprise suivent la séquence F-2026-001, F-2026-002, F-2026-003…", liens: ["/guide/mentions-obligatoires-facture"] },
  { slug: "pdp", terme: "Plateforme de dématérialisation partenaire (PDP)", definition: "Ancien nom des plateformes agréées : opérateurs privés agréés par l'administration fiscale pour transmettre les factures électroniques et les données de facturation.", explication: "On parle désormais de plateformes agréées. Elles transmettent les factures entre l'émetteur et le destinataire, et envoient les données à l'administration (e-reporting). Chaque entreprise choisit la sienne : le Portail public de facturation ne transmet pas les factures entre entreprises.", exemple: "Une entreprise choisit une plateforme agréée pour envoyer et recevoir ses factures électroniques.", liens: ["/guide/plateforme-agreee", "/guide/facture-electronique-2026"] },
  { slug: "penalites-retard", terme: "Pénalités de retard", definition: "Intérêts dus de plein droit par le débiteur en cas de paiement après la date d'échéance.", explication: "Le taux prévu ne peut pas être inférieur à 3 fois le taux d'intérêt légal ; à défaut de taux prévu, c'est le taux de refinancement de la BCE majoré de 10 points (article L441-10 du Code de commerce). Les pénalités courent automatiquement dès le lendemain de la date d'échéance, sans relance nécessaire. Le taux doit figurer sur la facture.", exemple: "Avec un taux de 12 %, une facture de 5 000 € payée avec 30 jours de retard génère 49,32 € de pénalités.", liens: ["/guide/delai-paiement-facture"] },
  { slug: "ppf", terme: "Portail public de facturation (PPF)", definition: "Plateforme de l'État au cœur de la réforme : elle tient l'annuaire des entreprises et centralise les données de facturation destinées à l'administration.", explication: "Depuis sa réorientation annoncée en octobre 2024, le PPF ne transmet pas les factures entre entreprises : chacune passe par une plateforme agréée de son choix. Le PPF tient l'annuaire qui indique sur quelle plateforme chaque entreprise reçoit ses factures, et reçoit les données transmises à l'administration fiscale. Chorus Pro reste le portail de facturation du secteur public.", exemple: "Avant d'envoyer une facture, la plateforme agréée de l'émetteur consulte l'annuaire du PPF pour trouver la plateforme du client.", liens: ["/guide/plateforme-agreee", "/guide/facture-electronique-2026"] },
  { slug: "proforma", terme: "Facture proforma", definition: "Document commercial sans valeur comptable ni fiscale, utilisé comme estimation ou pour les formalités douanières.", explication: "La facture proforma n'entre pas dans la numérotation des factures. Elle sert de devis à l'international ou de support pour les formalités bancaires et douanières. Une vraie facture doit être émise après la commande.", exemple: "Un exportateur émet une facture proforma pour permettre à son client étranger d'ouvrir un crédit documentaire.", liens: ["/modele/facture-proforma"] },
  { slug: "retenue-garantie", terme: "Retenue de garantie", definition: "Somme retenue par le maître d'ouvrage (5 % au maximum) pour garantir la bonne exécution des travaux.", explication: "La retenue de garantie est encadrée par la loi du 16 juillet 1971 (article L. 111-10-1 du CCH). Elle est consignée chez un tiers et libérée un an après la réception des travaux, sauf réserves non levées.", exemple: "Sur un chantier de 100 000 €, le maître d'ouvrage retient 5 000 € de garantie pendant un an.", liens: ["/modele/facture-situation", "/facturation/macon"] },
  { slug: "siret", terme: "SIRET", definition: "Numéro d'identification à 14 chiffres attribué par l'INSEE à chaque établissement d'une entreprise.", explication: "Le SIRET est composé du SIREN (9 chiffres, qui identifie l'entreprise) et du NIC (5 chiffres, qui identifie l'établissement). Il est obligatoire sur toutes les factures, tous les devis et tous les documents commerciaux.", exemple: "Une auto-entreprise mentionne son SIRET 123 456 789 00012 sur chaque facture.", liens: ["/guide/facture-auto-entrepreneur", "/guide/mentions-obligatoires-facture"] },
  { slug: "tva-intracommunautaire", terme: "Numéro de TVA intracommunautaire", definition: "Identifiant fiscal européen obligatoire pour les échanges de biens et de services au sein de l'UE.", explication: "Le numéro de TVA intracommunautaire est attribué par l'administration fiscale. Il est obligatoire sur les factures dès que la TVA est facturée, et indispensable pour les opérations intracommunautaires (article 242 nonies A de l'annexe II du CGI).", exemple: "FR 12 345678901 : le numéro commence par le code pays (FR), suivi de 11 caractères.", liens: ["/guide/mentions-obligatoires-facture", "/guide/facturer-etranger"] },
]

export function getTermeBySlug(slug: string): Terme | undefined {
  return GLOSSAIRE.find(t => t.slug === slug)
}
