export interface Terme {
  slug: string
  terme: string
  definition: string
  explication: string
  exemple: string
  liens: string[]
}

export const GLOSSAIRE: Terme[] = [
  { slug: "acompte", terme: "Acompte", definition: "Paiement partiel verse avant la realisation complete d'une prestation ou la livraison d'un bien.", explication: "L'acompte engage definitivement les deux parties. Contrairement aux arrhes, il ne peut pas etre recupere en cas d'annulation par le client. Une facture d'acompte doit etre emise des l'encaissement, avec TVA si applicable.", exemple: "Un artisan demande 30 % d'acompte a la signature du devis avant de commencer les travaux.", liens: ["/guide/facture-acompte", "/modele/facture-acompte"] },
  { slug: "arrhes", terme: "Arrhes", definition: "Somme versee a la commande permettant a chaque partie de se desengager.", explication: "Contrairement a l'acompte, les arrhes permettent l'annulation : le client perd les arrhes, le professionnel les rembourse au double. Sauf mention contraire, les sommes versees sont presumes etre des arrhes (article 1590 du Code civil).", exemple: "Un traiteur recoit 500 EUR d'arrhes pour une reservation de reception.", liens: ["/guide/devis-obligatoire"] },
  { slug: "avoir", terme: "Avoir (note de credit)", definition: "Document comptable qui annule ou corrige tout ou partie d'une facture emise.", explication: "L'avoir est obligatoire pour corriger une facture : il est interdit de supprimer ou modifier une facture deja emise. L'avoir porte un numero dans la sequence de facturation et doit referencer la facture d'origine.", exemple: "Un client retourne de la marchandise : le vendeur emet un avoir du montant correspondant.", liens: ["/guide/avoir-facture", "/modele/avoir-annulation"] },
  { slug: "autoliquidation", terme: "Autoliquidation de TVA", definition: "Mecanisme ou l'acheteur declare et deduit lui-meme la TVA, au lieu que le vendeur la facture.", explication: "Obligatoire en sous-traitance BTP depuis 2014 (article 283-2 nonies du CGI). Le sous-traitant facture en HT avec la mention « Autoliquidation ». L'entrepreneur principal declare la TVA sur sa declaration CA3.", exemple: "Un electricien sous-traitant facture 10 000 EUR HT sans TVA a l'entreprise generale.", liens: ["/guide/tva-autoliquidation-sous-traitance", "/facturation/electricien"] },
  { slug: "cgv", terme: "Conditions Generales de Vente (CGV)", definition: "Document contractuel detaillant les conditions de vente entre un professionnel et ses clients.", explication: "Les CGV sont obligatoires entre professionnels (article L441-1 du Code de commerce). Elles doivent etre communiquees a tout acheteur qui en fait la demande. Elles incluent les conditions de paiement, penalites de retard et garanties.", exemple: "Un consultant joint ses CGV a chaque devis, incluant ses delais de paiement et penalites.", liens: ["/guide/delai-paiement-facture"] },
  { slug: "devis", terme: "Devis", definition: "Document commercial detaillant les prestations proposees et leur prix, emis avant la realisation des travaux.", explication: "Le devis est obligatoire pour les travaux de plus de 150 EUR TTC et dans certains secteurs (demenagement, services a la personne). Un devis signe vaut engagement contractuel. Il doit mentionner la duree de validite.", exemple: "Un plombier etablit un devis de 2 500 EUR pour une renovation de salle de bain.", liens: ["/guide/devis-obligatoire", "/modele/devis-travaux"] },
  { slug: "e-reporting", terme: "E-reporting", definition: "Obligation de transmettre les donnees de facturation a l'administration fiscale pour les transactions B2C et internationales.", explication: "A partir de 2026, les entreprises doivent transmettre les donnees de leurs ventes aux particuliers et a l'international via une PDP ou le PPF. Le e-reporting complete la facturation electronique B2B.", exemple: "Un restaurant transmet mensuellement ses donnees de ventes B2C via sa plateforme de dematerialisation.", liens: ["/guide/facture-electronique-2026"] },
  { slug: "escompte", terme: "Escompte", definition: "Reduction accordee au client en echange d'un paiement anticipe, avant la date d'echeance.", explication: "L'escompte doit figurer sur la facture, meme s'il n'est pas accorde (mention « Pas d'escompte pour paiement anticipe »). Si un escompte est propose, ses conditions doivent etre clairement indiquees.", exemple: "Une facture propose 2 % d'escompte si le paiement est effectue sous 10 jours au lieu de 30.", liens: ["/guide/delai-paiement-facture", "/guide/mentions-obligatoires-facture"] },
  { slug: "factur-x", terme: "Factur-X", definition: "Format hybride de facturation electronique combinant un PDF lisible et des donnees XML structurees (norme EN 16931).", explication: "Factur-X est le format recommande pour les TPE et PME dans le cadre de la reforme 2026. Le PDF reste lisible par l'humain, tandis que le XML permet le traitement automatique par les logiciels comptables.", exemple: "Qonforme genere nativement des factures au format Factur-X pour la conformite 2026.", liens: ["/guide/facture-electronique-2026"] },
  { slug: "facture-electronique", terme: "Facture electronique", definition: "Facture emise et recue sous format electronique structure (Factur-X, UBL ou CII), transmise via une plateforme agreee.", explication: "A partir de septembre 2026, toutes les entreprises assujetties a la TVA doivent etre capables de recevoir des factures electroniques. L'obligation d'emission sera progressive. Un simple PDF envoye par email n'est pas une facture electronique au sens de la reforme.", exemple: "Une entreprise envoie sa facture Factur-X via une PDP agreee a son client.", liens: ["/guide/facture-electronique-2026"] },
  { slug: "fec", terme: "Fichier des Ecritures Comptables (FEC)", definition: "Export standardise de la comptabilite d'une entreprise, obligatoire en cas de controle fiscal.", explication: "Le FEC est un fichier au format texte (CSV) contenant toutes les ecritures comptables de l'exercice. Il doit etre presentable a la demande de l'administration fiscale (article L47 A-I du LPF). Son absence est sanctionnee d'une amende de 5 000 EUR.", exemple: "L'expert-comptable genere le FEC annuel via le logiciel de facturation pour le depot fiscal.", liens: ["/guide/conservation-factures"] },
  { slug: "franchise-tva", terme: "Franchise en base de TVA", definition: "Regime fiscal dispensant les petites entreprises de facturer et declarer la TVA.", explication: "La franchise s'applique sous les seuils de CA : 36 800 EUR pour les services, 91 900 EUR pour la vente (article 293 B du CGI). La mention « TVA non applicable, article 293 B du CGI » doit figurer sur chaque facture.", exemple: "Un auto-entrepreneur en dessous des seuils facture 1 000 EUR HT sans ligne de TVA.", liens: ["/guide/facture-auto-entrepreneur", "/facturation/auto-entrepreneur"] },
  { slug: "garantie-decennale", terme: "Garantie decennale", definition: "Assurance obligatoire couvrant les malfacons affectant la solidite d'un ouvrage pendant 10 ans apres la reception.", explication: "Tout constructeur doit souscrire une assurance decennale (article 1792 du Code civil). Les coordonnees de l'assureur (nom, numero de contrat, couverture geographique) doivent figurer sur les devis et factures.", exemple: "Un macon mentionne sur son devis : « Decennale : AXA, contrat n° 123456, couverture France entiere ».", liens: ["/facturation/macon", "/modele/devis-travaux"] },
  { slug: "indemnite-recouvrement", terme: "Indemnite forfaitaire de recouvrement", definition: "Somme de 40 EUR due de plein droit par le debiteur en cas de retard de paiement entre professionnels.", explication: "Cette indemnite est exigible sans mise en demeure prealable, des le premier jour de retard (article D441-5 du Code de commerce). Elle doit etre mentionnee sur chaque facture. Si les frais reels depassent 40 EUR, le creancier peut demander une indemnisation complementaire.", exemple: "Un fournisseur ajoute 40 EUR d'indemnite de recouvrement a sa relance pour facture impayee.", liens: ["/guide/delai-paiement-facture", "/modele/lettre-relance-impaye"] },
  { slug: "injonction-payer", terme: "Injonction de payer", definition: "Procedure judiciaire simplifiee permettant de recouvrer une creance impayee sans audience.", explication: "La requete est deposee aupres du tribunal competent (tribunal de commerce pour les litiges B2B). Le juge rend une ordonnance dans un delai de quelques semaines. Le debiteur dispose d'un mois pour faire opposition.", exemple: "Apres une mise en demeure restee sans reponse, un artisan depose une requete d'injonction de payer.", liens: ["/guide/facture-impayee"] },
  { slug: "mention-obligatoire", terme: "Mentions obligatoires", definition: "Informations devant figurer sur toute facture sous peine d'amende (15 EUR par mention manquante).", explication: "Les mentions incluent : identite vendeur/acheteur, numero de facture sequentiel, date, designation des prestations, prix, TVA, conditions de paiement, penalites de retard et indemnite de recouvrement.", exemple: "Une facture sans numero SIRET expose le professionnel a une amende de 15 EUR par facture.", liens: ["/guide/mentions-obligatoires-facture"] },
  { slug: "mise-en-demeure", terme: "Mise en demeure", definition: "Courrier formel (recommande AR) exigeant le paiement d'une dette et constituant un prealable a l'action en justice.", explication: "La mise en demeure doit preciser les references des factures impayees, le montant du avec penalites, et le delai accorde (generalement 8 jours). Elle constitue la preuve juridique de la tentative de recouvrement amiable.", exemple: "Un prestataire envoie une mise en demeure LRAR apres deux relances restees sans reponse.", liens: ["/guide/facture-impayee", "/modele/lettre-relance-impaye"] },
  { slug: "note-honoraires", terme: "Note d'honoraires", definition: "Document equivalent a une facture, utilise par les professions liberales et de sante.", explication: "La note d'honoraires suit les memes regles que la facture (mentions obligatoires, numerotation sequentielle). Elle est utilisee par les medecins, osteopathes, avocats, architectes et autres professions liberales.", exemple: "Un osteopathe remet une note d'honoraires de 60 EUR apres chaque consultation.", liens: ["/facturation/osteopathe", "/facturation/avocat"] },
  { slug: "numero-facture", terme: "Numero de facture", definition: "Identifiant unique et sequentiel attribue a chaque facture, obligatoire et inalterable.", explication: "La numerotation doit etre chronologique et continue, sans trous ni doublons. Un prefixe est autorise (ex : F-2026-001). Il est interdit de supprimer un numero : en cas d'erreur, il faut emettre un avoir.", exemple: "Les factures d'une entreprise suivent la sequence F-2026-001, F-2026-002, F-2026-003...", liens: ["/guide/mentions-obligatoires-facture"] },
  { slug: "pdp", terme: "Plateforme de Dematerialisation Partenaire (PDP)", definition: "Intermediaire agree par l'administration fiscale pour transmettre les factures electroniques et les donnees de facturation.", explication: "Les PDP sont des entreprises privees immatriculees aupres de la DGFiP. Elles assurent la transmission des factures entre emetteur et destinataire, ainsi que l'envoi des donnees a l'administration (e-reporting). Alternative au Portail Public de Facturation (PPF).", exemple: "Une entreprise choisit une PDP agreee pour transmettre ses factures electroniques a ses clients.", liens: ["/guide/facture-electronique-2026"] },
  { slug: "penalites-retard", terme: "Penalites de retard", definition: "Interets dus de plein droit par le debiteur en cas de paiement apres la date d'echeance.", explication: "Le taux minimum est de 3 fois le taux d'interet legal (article L441-10 du Code de commerce). Les penalites courent automatiquement des le lendemain de la date d'echeance, sans relance necessaire. Le taux doit figurer sur la facture.", exemple: "Avec un taux de 12 %, une facture de 5 000 EUR payee avec 30 jours de retard genere 49,32 EUR de penalites.", liens: ["/guide/delai-paiement-facture"] },
  { slug: "ppf", terme: "Portail Public de Facturation (PPF)", definition: "Plateforme gratuite operee par l'Etat pour l'emission, la reception et la transmission des factures electroniques.", explication: "Le PPF (ex-Chorus Pro) est une alternative gratuite aux PDP pour les entreprises. Il assure la transmission des factures B2B et du e-reporting a l'administration fiscale. Son utilisation n'est pas obligatoire si l'entreprise passe par une PDP.", exemple: "Une micro-entreprise utilise le PPF gratuit pour recevoir ses factures electroniques.", liens: ["/guide/facture-electronique-2026"] },
  { slug: "proforma", terme: "Facture proforma", definition: "Document commercial sans valeur comptable ni fiscale, utilise comme estimation ou pour les formalites douanieres.", explication: "La facture proforma n'entre pas dans la numerotation des factures. Elle sert de devis pour l'international ou de support pour les formalites bancaires et douanieres. Une vraie facture doit etre emise apres la commande.", exemple: "Un exportateur emet une facture proforma pour permettre a son client etranger d'ouvrir un credit documentaire.", liens: ["/modele/facture-proforma"] },
  { slug: "retenue-garantie", terme: "Retenue de garantie", definition: "Somme retenue par le maitre d'ouvrage (max 5 %) pour garantir la bonne execution des travaux.", explication: "La retenue de garantie est encadree par la loi du 16 juillet 1971 (article L. 111-10-1 du CCH). Elle est consignee chez un tiers et liberee un an apres la reception des travaux, sauf reserves non levees.", exemple: "Sur un chantier de 100 000 EUR, le maitre d'ouvrage retient 5 000 EUR de garantie pendant un an.", liens: ["/modele/facture-situation", "/facturation/macon"] },
  { slug: "siret", terme: "SIRET", definition: "Numero d'identification a 14 chiffres attribue a chaque etablissement d'une entreprise par l'INSEE.", explication: "Le SIRET est compose du SIREN (9 chiffres, identifiant l'entreprise) + NIC (5 chiffres, identifiant l'etablissement). Il est obligatoire sur toutes les factures, devis et documents commerciaux.", exemple: "Une auto-entreprise mentionne son SIRET 123 456 789 00012 sur chaque facture.", liens: ["/guide/facture-auto-entrepreneur", "/guide/mentions-obligatoires-facture"] },
  { slug: "tva-intracommunautaire", terme: "Numero de TVA intracommunautaire", definition: "Identifiant fiscal europeen obligatoire pour les echanges de biens et services au sein de l'UE.", explication: "Le numero de TVA intracommunautaire est attribue par l'administration fiscale. Il est obligatoire sur les factures des que la TVA est facturee, et indispensable pour les operations intracommunautaires (article 242 nonies A annexe II du CGI).", exemple: "FR 12 345678901 — le numero commence par le code pays (FR) suivi de 11 caracteres.", liens: ["/guide/mentions-obligatoires-facture", "/guide/facturer-etranger"] },
]

export function getTermeBySlug(slug: string): Terme | undefined {
  return GLOSSAIRE.find(t => t.slug === slug)
}
