export interface Metier {
  slug: string
  nom: string
  titre: string
  description: string
  motsCles: string[]
  features: { titre: string; texte: string }[]
  obligations: string[]
  faq: { question: string; reponse: string }[]
  metiersProches: string[]
}

/*
 * Fonctions affichées sur les pages métier : uniquement celles que le produit
 * livre aujourd'hui (DECISIONS-STRATEGIQUES.md § 10). Une fonction en
 * préparation (autoliquidation, acomptes, situations, suivi de chantier,
 * factures récurrentes, suivi d'ouverture…) n'entre ici qu'une fois livrée.
 */
const BTP_FEATURES = [
  { titre: "Devis détaillés", texte: "Créez des devis avec vos lignes de main-d'œuvre, de matériaux et de déplacement, et un taux de TVA par ligne (5,5 %, 10 % ou 20 %)." },
  { titre: "Du devis à la facture", texte: "Une fois le devis accepté, transformez-le en facture en un clic, sans rien ressaisir." },
  { titre: "Décennale sur vos documents", texte: "Enregistrez une fois votre assurance décennale et vos mentions : elles figurent ensuite sur chaque devis et chaque facture." },
]

const SERVICE_FEATURES = [
  { titre: "Devis gratuits et illimités", texte: "Préparez autant de devis que nécessaire, sans abonnement, puis transformez-les en facture une fois acceptés." },
  { titre: "Suivi des paiements", texte: "Voyez d'un coup d'œil les factures payées, en attente et en retard." },
  { titre: "Relances par email", texte: "Relancez une facture impayée en un clic, ou laissez partir les relances automatiques 30 et 45 jours après l'échéance." },
]

const SANTE_FEATURES = [
  { titre: "Exonération de TVA", texte: "Facturez avec une TVA à 0 % et enregistrez une fois la mention d'exonération (article 261-4-1° du CGI) : elle figure ensuite sur chaque facture." },
  { titre: "Numérotation séquentielle", texte: "Numérotation chronologique et continue, avec votre préfixe et l'année (ex. F-2026-001)." },
  { titre: "Catalogue de prestations", texte: "Enregistrez vos actes et leurs tarifs une fois, puis ajoutez-les en un clic à vos factures." },
]

const COMMON_FEATURES = [
  { titre: "Envoi par email", texte: "Envoyez vos factures et devis par email depuis l'application, le PDF en pièce jointe." },
  { titre: "Avoirs", texte: "Une facture émise ne se modifie pas : corrigez-la par un avoir, numéroté à la suite des précédents." },
  { titre: "Export comptable FEC", texte: "Exportez vos factures et vos avoirs au format FEC (Fichier des écritures comptables) pour votre expert-comptable." },
]

const DESCRIPTIONS: Record<string, string> = {
  plombier: "Logiciel de facturation pour plombier : devis détaillés, TVA par ligne (5,5, 10 ou 20 %), assurance décennale sur vos documents. Devis gratuits et illimités.",
  electricien: "Facturez vos travaux d'électricité avec les mentions NF C 15-100, l'attestation Consuel et l'assurance décennale. Devis gratuits et illimités.",
  macon: "Logiciel de facturation maçonnerie : devis gros œuvre, TVA 10 % rénovation / 20 % neuf, export FEC comptable. Devis gratuits et illimités.",
  peintre: "Créez vos devis peinture au m² avec le détail des couches, de la sous-couche et des fournitures. TVA 10 % rénovation. Devis gratuits et illimités.",
  carreleur: "Devis et factures de pose de carrelage : surfaces, matériaux, ragréage. TVA adaptée au type de travaux. Devis gratuits et illimités.",
  menuisier: "Facturez vos travaux de menuiserie sur mesure : fabrication, pose, finitions. Marquage CE et décennale. Devis gratuits et illimités.",
  couvreur: "Logiciel de facturation couverture et toiture : devis tuiles, ardoises, zinc, étanchéité, mention décennale. Devis gratuits et illimités.",
  plaquiste: "Facturez vos chantiers placo au m² : cloisons, plafonds, isolation, bandes et enduit. Export comptable FEC. Devis gratuits et illimités.",
  chauffagiste: "Facturez installations et dépannages de chauffage : TVA à 5,5 % ou 10 %, mention RGE, attestation gaz, entretien annuel. Devis gratuits et illimités.",
  serrurier: "Factures et devis de serrurerie : interventions d'urgence, pose de serrures, tarifs transparents. Devis gratuits et illimités.",
  "auto-entrepreneur": "Facturez en micro-entreprise : mention « TVA non applicable, art. 293 B du CGI », numérotation continue, seuils de franchise expliqués. Devis gratuits.",
  consultant: "Logiciel de facturation pour consultant : taux journalier, forfait de mission, frais de déplacement, conditions de paiement. Devis gratuits et illimités.",
  "developpeur-freelance": "Facturez vos prestations de développement web et logiciel : livrables, cession de droits, maintenance. Devis gratuits et illimités.",
  graphiste: "Devis et factures de création graphique : conception, déclinaisons, cession de droits d'exploitation. Devis gratuits et illimités.",
  photographe: "Facturez vos reportages photo : prise de vue, retouche, cession de droits d'auteur (CPI L131-3). Devis gratuits et illimités.",
  formateur: "Factures de formation : numéro de déclaration d'activité (NDA), exonération de TVA art. 261-4-4° du CGI, OPCO, Qualiopi. Devis gratuits et illimités.",
  coach: "Facturez vos séances de coaching professionnel : forfait, séance unique, présentiel ou visio. Devis gratuits et illimités.",
  "community-manager": "Facturez vos prestations de community management : forfait mensuel, création de contenu, reporting. Devis gratuits et illimités.",
  traducteur: "Facturez vos traductions au mot ou au feuillet : langues, spécialité, cession de droits. Devis gratuits et illimités.",
  coiffeur: "Facturation pour salon de coiffure : note au-delà de 25 €, factures aux clients professionnels, TVA à 20 %, affichage des prix obligatoire.",
  estheticienne: "Facturez vos soins esthétiques : prestations détaillées, forfaits, TVA à 20 %, note obligatoire au-delà de 25 €. Devis gratuits et illimités.",
  paysagiste: "Devis et factures d'entretien de jardin et d'aménagement paysager : crédit d'impôt SAP, RC pro, TVA. Devis gratuits et illimités.",
  "architecte-interieur": "Facturez vos honoraires d'architecture intérieure : pourcentage des travaux, forfait ou régie. Devis gratuits et illimités.",
  traiteur: "Devis de traiteur détaillés : menu, convives, personnel, matériel, livraison, TVA à 5,5, 10 ou 20 %. Devis gratuits et illimités.",
  fleuriste: "Facturez vos compositions florales avec une TVA à 10 % sur les fleurs et à 20 % sur les accessoires. Devis gratuits et illimités.",
  osteopathe: "Facturation pour ostéopathe : exonération de TVA (art. 261-4-1° du CGI), numéro ADELI ou RPPS, mentions obligatoires de la note d'honoraires.",
  kinesitherapeute: "Facturation pour kinésithérapeute : actes hors nomenclature, numéro RPPS, exonération de TVA, et les règles de la feuille de soins et du tiers payant.",
  "infirmier-liberal": "Facturation des infirmiers libéraux : règles Sesam-Vitale, majorations, indemnités de déplacement, et factures des prestations hors nomenclature.",
  dieteticien: "Facturation pour diététicien : consultations exonérées de TVA, numéro ADELI, note d'honoraires pour le remboursement par la mutuelle.",
  comptable: "Facturation pour cabinet comptable : honoraires, lettre de mission, déontologie de l'OEC, export FEC de vos ventes. Devis gratuits et illimités.",
  avocat: "Facturez vos honoraires d'avocat : convention d'honoraires, compte CARPA, provisions, TVA à 20 %. Devis gratuits et illimités.",
  "agent-immobilier": "Logiciel de facturation pour agent immobilier : commissions, mandats, barème d'honoraires, carte professionnelle T. Devis gratuits et illimités.",
  boulanger: "Facturation pour boulangerie-pâtisserie : factures aux professionnels, TVA à 5,5 %, 10 % ou 20 %, règles des tickets de caisse et normes HACCP.",
  vtc: "Facturez vos courses VTC : notes de course, carte professionnelle, licence de transport, RC exploitation. Devis gratuits et illimités.",
  "femme-de-menage": "Facturez vos prestations de ménage et de nettoyage : crédit d'impôt SAP de 50 %, CESU, convention collective. Devis gratuits et illimités.",
  informaticien: "Facturez vos dépannages et maintenances informatiques : devis obligatoire au-delà de 150 €, garantie de conformité. Devis gratuits et illimités.",
  jardinier: "Facturez vos prestations de jardinage : crédit d'impôt SAP de 50 %, CESU, entretien saisonnier. Devis gratuits et illimités.",
  demenageur: "Devis et factures de déménagement : licence de transport, lettre de voiture, assurance dommages. Devis gratuits et illimités.",
  taxi: "Facturez vos courses de taxi : licence ADS, taximètre, note obligatoire au-delà de 25 €, TVA à 10 % sur le transport de voyageurs.",
}

function metier(
  slug: string,
  nom: string,
  categorie: "btp" | "service" | "sante" | "artisanat",
  motsCles: string[],
  obligations: string[],
  faq: { question: string; reponse: string }[],
  metiersProches: string[] = [],
): Metier {
  const catFeatures = categorie === "btp" ? BTP_FEATURES : categorie === "sante" ? SANTE_FEATURES : SERVICE_FEATURES
  return {
    slug,
    nom,
    titre: `Logiciel de facturation pour ${nom}`,
    description: DESCRIPTIONS[slug] ?? `Créez et envoyez vos devis et factures de ${nom.toLowerCase()} en quelques clics, avec les mentions obligatoires. Devis gratuits et illimités.`,
    motsCles: [`facturation ${nom.toLowerCase()}`, `facture ${nom.toLowerCase()}`, `devis ${nom.toLowerCase()}`, `logiciel facturation ${nom.toLowerCase()}`, ...motsCles],
    features: [...catFeatures, ...COMMON_FEATURES],
    obligations,
    faq,
    metiersProches,
  }
}

export const METIERS: Metier[] = [
  // ── BTP ──
  metier("plombier", "Plombier", "btp",
    ["facture plomberie", "devis plomberie"],
    ["Devis obligatoire avant travaux (> 150 €)", "Mention de l'assurance décennale sur les devis et factures", "Garantie de parfait achèvement d'un an"],
    [
      { question: "Quelles mentions obligatoires sur une facture de plomberie ?", reponse: "Outre les mentions légales classiques (SIRET, date, numéro séquentiel), une facture de plomberie doit mentionner l'assurance décennale (nom, numéro de contrat, couverture géographique) et le détail des prestations (main-d'œuvre, fournitures, déplacement)." },
      { question: "Un plombier doit-il faire un devis ?", reponse: "Oui, un devis est obligatoire pour tout travail dont le montant dépasse 150 € TTC, ou sur demande du client. Le devis doit détailler les prestations, les matériaux, les délais et le prix total." },
      { question: "Comment facturer un dépannage d'urgence en plomberie ?", reponse: "Le dépannage d'urgence peut être facturé sans devis préalable si le montant est inférieur à 150 €. Mentionnez clairement le tarif horaire, les majorations éventuelles (nuit, week-end) et les fournitures utilisées." },
      { question: "Quel taux de TVA appliquer en plomberie ?", reponse: "Le taux de TVA dépend du type de travaux : 20 % pour les constructions neuves, 10 % pour les travaux de rénovation dans un logement de plus de 2 ans (article 279-0 bis du CGI), et 5,5 % pour les travaux d'amélioration de la performance énergétique." },
      { question: "La facturation électronique Factur-X est-elle obligatoire pour un plombier en 2026 ?", reponse: "Depuis le 1er septembre 2026, toute entreprise, artisans du BTP compris, doit pouvoir recevoir des factures électroniques. L'émission devient obligatoire pour les TPE et PME au 1er septembre 2027 : vos factures aux clients professionnels devront alors partir dans un format structuré (Factur-X, UBL ou CII), par une plateforme agréée. Qonforme joint déjà un fichier XML Factur-X au PDF de vos factures ; l'envoi par une plateforme agréée est en préparation." },
    ],
    ["electricien", "chauffagiste", "macon", "carreleur"],
  ),
  metier("electricien", "Électricien", "btp",
    ["facture electricite", "devis electricite", "norme NF C 15-100"],
    ["Attestation de conformité Consuel après travaux", "Respect de la norme NF C 15-100", "Assurance décennale obligatoire"],
    [
      { question: "Quelles normes mentionner sur une facture d'électricité ?", reponse: "La facture doit faire référence à la norme NF C 15-100 si les travaux concernent une installation neuve ou une rénovation complète. Mentionnez aussi l'attestation Consuel si applicable." },
      { question: "Un électricien doit-il mentionner son assurance décennale ?", reponse: "Oui, l'assurance décennale est obligatoire pour tous les travaux de construction et rénovation. Elle doit figurer sur les devis et factures avec le nom de l'assureur, le numéro de contrat et la zone géographique couverte." },
      { question: "Quel taux de TVA pour des travaux d'électricité ?", reponse: "Le taux est de 20 % pour les constructions neuves, 10 % pour la rénovation de logements de plus de 2 ans (article 279-0 bis du CGI), et 5,5 % pour les travaux d'amélioration énergétique (isolation, chauffage performant)." },
      { question: "Comment facturer au forfait ou au mètre linéaire en électricité ?", reponse: "Les deux modes sont courants : le forfait convient aux installations complètes (tableau, circuit), tandis que le mètre linéaire est utilisé pour le câblage et les chemins de câbles. Détaillez toujours la méthode de calcul sur le devis." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un électricien ?", reponse: "Depuis le 1er septembre 2026, tout électricien doit pouvoir recevoir des factures électroniques. L'émission suit la taille de l'entreprise : depuis le 1er septembre 2026 pour les grandes entreprises et les ETI, à partir du 1er septembre 2027 pour les TPE et PME. Les factures aux clients professionnels passeront alors par une plateforme agréée, dans un format structuré comme Factur-X." },
    ],
    ["plombier", "chauffagiste", "plaquiste", "couvreur"],
  ),
  metier("macon", "Maçon", "btp",
    ["facture maconnerie", "devis maconnerie", "gros oeuvre"],
    ["Assurance décennale obligatoire", "Garantie de parfait achèvement", "Devis détaillé obligatoire pour travaux > 150 €"],
    [
      { question: "Comment facturer des travaux de maçonnerie ?", reponse: "Détaillez chaque poste : terrassement, fondations, élévation des murs, fournitures (parpaings, ciment, ferraillage). Séparez main-d'œuvre et matériaux avec les taux de TVA applicables (10% rénovation, 20% neuf)." },
      { question: "Quel taux de TVA pour des travaux de maçonnerie ?", reponse: "Le taux dépend du type de travaux : 20% pour la construction neuve, 10% pour la rénovation/amélioration de logements de plus de 2 ans, 5,5% pour les travaux d'amélioration énergétique." },
      { question: "L'assurance décennale est-elle obligatoire pour un maçon ?", reponse: "Oui, la garantie décennale est obligatoire pour tout constructeur au sens de l'article 1792 du Code civil. Elle couvre les dommages compromettant la solidité de l'ouvrage pendant 10 ans. Ses références doivent figurer sur tous les devis et factures." },
      { question: "Comment facturer la sous-traitance en maçonnerie (autoliquidation) ?", reponse: "En cas de sous-traitance BTP, c'est le donneur d'ordre qui reverse la TVA (article 283-2 nonies du CGI). Le sous-traitant maçon émet une facture HT avec la mention « Autoliquidation de la TVA » sans collecter de TVA." },
      { question: "La facturation électronique Factur-X concerne-t-elle les maçons ?", reponse: "Oui, la réforme de la facturation électronique s'applique à tous les professionnels du BTP, maçons compris. Ils doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026, et les TPE et PME devront émettre leurs factures B2B dans un format structuré (Factur-X, UBL ou CII), par une plateforme agréée, à partir du 1er septembre 2027." },
    ],
    ["plombier", "carreleur", "couvreur", "peintre"],
  ),
  metier("peintre", "Peintre en bâtiment", "btp",
    ["facture peinture", "devis peinture batiment"],
    ["Devis détaillé avec surfaces et nombre de couches", "Assurance responsabilité civile professionnelle", "Respect des normes environnementales (COV)"],
    [
      { question: "Comment établir un devis de peinture ?", reponse: "Un devis de peinture doit détailler : les surfaces à peindre (en m²), le nombre de couches, le type de peinture, la préparation des supports (ponçage, enduit, sous-couche), et séparer main-d'œuvre et fournitures." },
      { question: "Quel taux de TVA pour des travaux de peinture ?", reponse: "10% pour la rénovation de logements achevés depuis plus de 2 ans, 20% pour les constructions neuves ou les locaux professionnels." },
      { question: "Un peintre en bâtiment doit-il souscrire une assurance décennale ?", reponse: "Oui, la décennale est obligatoire dès lors que les travaux de peinture affectent l'étanchéité ou la protection de l'ouvrage (peinture extérieure, imperméabilisation). Pour la peinture intérieure décorative, la RC professionnelle suffit généralement." },
      { question: "Comment facturer des travaux de peinture au m² ?", reponse: "Indiquez la surface totale en m², le prix unitaire au m² (qui inclut main-d'œuvre et fournitures ou les sépare), le nombre de couches et le type de finition. Ce mode de facturation est le plus transparent pour le client." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un peintre ?", reponse: "Comme tous les artisans du BTP, les peintres en bâtiment doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, les TPE et PME devront aussi émettre leurs factures aux clients professionnels dans un format structuré, par une plateforme agréée. Qonforme joint déjà un fichier XML Factur-X au PDF de vos factures ; l'envoi par une plateforme agréée est en préparation." },
    ],
    ["plaquiste", "carreleur", "macon", "menuisier"],
  ),
  metier("carreleur", "Carreleur", "btp",
    ["facture carrelage", "devis pose carrelage"],
    ["Assurance décennale obligatoire", "Devis avec détail des surfaces et matériaux"],
    [
      { question: "Comment facturer une pose de carrelage ?", reponse: "Détaillez la surface (m²), le type de carrelage (grès cérame, faïence), la pose (droite, diagonale, décalée), les fournitures (colle, joints, croisillons) et les travaux de préparation (ragréage, chape)." },
      { question: "Quel taux de TVA pour la pose de carrelage ?", reponse: "Le taux réduit de 10 % s'applique pour la pose de carrelage dans un logement de plus de 2 ans (article 279-0 bis du CGI). Le taux normal de 20 % s'applique pour les constructions neuves et les locaux professionnels." },
      { question: "L'assurance décennale est-elle obligatoire pour un carreleur ?", reponse: "Oui, le carreleur réalise des travaux d'ouvrage et doit souscrire une assurance décennale (article 1792 du Code civil). Cette garantie couvre les défauts de pose (infiltrations, décollements) pendant 10 ans après la réception des travaux." },
      { question: "Comment établir un devis de carrelage au m² ?", reponse: "Indiquez la surface totale en m², le prix au m² pour la fourniture et la pose séparément, les découpes spéciales (angles, plinthes), et les travaux préparatoires. Précisez le type de pose car une pose diagonale coûte plus cher qu'une pose droite." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un carreleur ?", reponse: "Les carreleurs doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, les TPE et PME devront émettre dans un format structuré (Factur-X, UBL ou CII) toutes leurs factures B2B, y compris les factures de sous-traitance en autoliquidation de TVA." },
    ],
    ["macon", "peintre", "plombier", "menuisier"],
  ),
  metier("menuisier", "Menuisier", "btp",
    ["facture menuiserie", "devis menuiserie"],
    ["Assurance décennale pour les ouvrages structurels", "Marquage CE pour les menuiseries extérieures"],
    [
      { question: "Comment facturer des travaux de menuiserie ?", reponse: "Distinguez la fabrication sur mesure (matériaux, heures d'atelier) de la pose (déplacement, installation, finitions). Précisez le type de bois et les traitements appliqués." },
      { question: "Quel taux de TVA pour des travaux de menuiserie ?", reponse: "Le taux de 10 % s'applique à la pose de menuiseries dans un logement de plus de 2 ans. Le taux de 5,5 % s'applique aux menuiseries améliorant la performance énergétique (fenêtres isolantes, portes d'entrée). Le taux de 20 % s'applique au neuf." },
      { question: "L'assurance décennale est-elle obligatoire pour un menuisier ?", reponse: "Oui, pour les ouvrages structurels (charpente, escalier, menuiseries extérieures). La décennale couvre les dommages compromettant la solidité ou rendant l'ouvrage impropre à sa destination pendant 10 ans (article 1792 du Code civil)." },
      { question: "Comment facturer la fabrication sur mesure et la pose séparément ?", reponse: "Créez deux sections distinctes sur votre facture : la fabrication (matériaux bois, quincaillerie, heures d'atelier) et la pose (déplacement, installation, ajustements). Ce détail facilite l'application des bons taux de TVA." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un menuisier ?", reponse: "Les menuisiers doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, les TPE et PME devront émettre leurs factures aux clients professionnels au format électronique : elles transiteront par une plateforme agréée." },
    ],
    ["couvreur", "peintre", "plaquiste", "carreleur"],
  ),
  metier("couvreur", "Couvreur", "btp",
    ["facture toiture", "devis couverture"],
    ["Assurance décennale obligatoire", "Respect des DTU couverture"],
    [
      { question: "Quelles mentions sur un devis de couverture ?", reponse: "Le devis doit préciser le type de couverture (tuiles, ardoises, zinc), la surface en m², les travaux d'étanchéité, la pose de gouttières, et l'évacuation des déchets. L'assurance décennale est impérative." },
      { question: "Quel taux de TVA pour des travaux de toiture ?", reponse: "Le taux de 10 % s'applique à la réfection de toiture d'un logement de plus de 2 ans. Le taux de 5,5 % concerne les travaux d'isolation de toiture améliorant la performance énergétique. Le taux normal de 20 % s'applique aux constructions neuves." },
      { question: "L'assurance décennale est-elle obligatoire pour un couvreur ?", reponse: "Oui, absolument. La toiture étant un élément de clos et de couvert, elle relève de la garantie décennale (article 1792 du Code civil). Tout couvreur doit mentionner son assurance décennale sur ses devis et factures." },
      { question: "Comment facturer des travaux de couverture au m² ?", reponse: "Indiquez la surface totale en m², le prix au m² pour la dépose de l'ancienne couverture, la fourniture des matériaux neufs et la pose. Séparez les postes accessoires : zinguerie, gouttières, ventilation, échafaudage." },
      { question: "Un couvreur est-il concerné par la facturation Factur-X 2026 ?", reponse: "Oui. Les couvreurs doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026, et les TPE et PME devront émettre leurs factures B2B au format électronique à partir du 1er septembre 2027, factures de sous-traitance comprises." },
    ],
    ["macon", "menuisier", "plaquiste", "chauffagiste"],
  ),
  metier("plaquiste", "Plaquiste", "btp",
    ["facture placo", "devis plaquiste", "cloison seche"],
    ["Assurance décennale", "Respect des DTU plâtrerie"],
    [
      { question: "Comment facturer des travaux de plâtrerie ?", reponse: "Facturez au m² pour les cloisons et plafonds. Détaillez : type de plaques (BA13, hydrofuge, phonique), ossature, isolation, bandes et finitions (enduit, ponçage)." },
      { question: "Quel taux de TVA pour des travaux de plaquiste ?", reponse: "Le taux réduit de 10 % s'applique aux travaux de cloisons et faux plafonds dans un logement de plus de 2 ans. Le taux de 5,5 % concerne les travaux d'isolation thermique (doublage avec isolant). Le neuf est à 20 %." },
      { question: "Un plaquiste doit-il souscrire une assurance décennale ?", reponse: "Oui, les travaux de plâtrerie sèche (cloisons, doublages, faux plafonds) constituent des ouvrages couverts par la garantie décennale dès lors qu'ils participent à la solidité ou à l'habitabilité du bâtiment (article 1792 du Code civil)." },
      { question: "Comment facturer la sous-traitance en plâtrerie avec autoliquidation ?", reponse: "Si vous intervenez comme sous-traitant, facturez HT avec la mention « Autoliquidation — article 283-2 nonies du CGI ». C'est le donneur d'ordre qui déclare et reverse la TVA. Aucune TVA ne doit apparaître sur votre facture." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un plaquiste ?", reponse: "Les plaquistes doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, les TPE et PME devront émettre leurs factures aux clients professionnels dans un format structuré (Factur-X, UBL ou CII). Le e-reporting s'appliquera aussi aux ventes aux particuliers." },
    ],
    ["peintre", "electricien", "menuisier", "macon"],
  ),
  metier("chauffagiste", "Chauffagiste", "btp",
    ["facture chauffage", "devis installation chauffage"],
    ["Qualification RGE pour les aides énergétiques", "Attestation de conformité gaz"],
    [
      { question: "Un chauffagiste doit-il être RGE ?", reponse: "La qualification RGE (Reconnu Garant de l'Environnement) n'est pas obligatoire mais elle permet à vos clients de bénéficier des aides (MaPrimeRénov', CEE). Mentionnez-la sur vos devis et factures." },
      { question: "Quel taux de TVA pour l'installation d'un chauffage ?", reponse: "Le taux de 5,5 % s'applique aux équipements de chauffage performants (pompe à chaleur, chaudière à condensation) dans un logement de plus de 2 ans. Le taux de 10 % s'applique aux autres travaux de rénovation. Le neuf est à 20 %." },
      { question: "L'assurance décennale est-elle obligatoire pour un chauffagiste ?", reponse: "Oui, les installations de chauffage sont des éléments d'équipement indissociables du bâtiment couverts par la garantie décennale (article 1792 du Code civil). Le chauffagiste doit mentionner son assureur et son numéro de contrat sur chaque devis." },
      { question: "Comment facturer l'entretien annuel d'une chaudière ?", reponse: "L'entretien annuel obligatoire (décret n° 2009-649) se facture généralement au forfait. Détaillez les opérations effectuées (nettoyage, vérifications, mesure de combustion) et remettez l'attestation d'entretien au client." },
      { question: "Un chauffagiste est-il concerné par Factur-X 2026 ?", reponse: "Oui, comme tous les professionnels du BTP : réception des factures électroniques depuis le 1er septembre 2026 et, pour les TPE et PME, émission des factures B2B dans un format structuré à partir du 1er septembre 2027. Les factures aux particuliers relèveront du e-reporting." },
    ],
    ["plombier", "electricien", "couvreur", "macon"],
  ),
  metier("serrurier", "Serrurier", "btp",
    ["facture serrurerie", "devis serrurier"],
    ["Affichage des tarifs obligatoire", "Devis obligatoire avant intervention (sauf urgence < 150 €)"],
    [
      { question: "Comment facturer une intervention de serrurerie ?", reponse: "Détaillez le déplacement, la main-d'œuvre (avec tarif horaire), les fournitures (cylindre, serrure, poignée) et les majorations éventuelles (nuit, dimanche). Pour les urgences < 150 €, le devis n'est pas obligatoire." },
      { question: "Quel taux de TVA pour des travaux de serrurerie ?", reponse: "Le taux de 10 % s'applique aux travaux de remplacement de serrures et blindage de portes dans un logement de plus de 2 ans. Le taux de 20 % s'applique aux constructions neuves et aux locaux professionnels." },
      { question: "Un serrurier doit-il afficher ses tarifs ?", reponse: "Oui, l'arrêté du 24 janvier 2017 impose l'affichage des tarifs pour les prestations de dépannage, réparation et entretien. Le serrurier doit afficher ses tarifs TTC (déplacement, main-d'œuvre horaire, majorations) dans son véhicule et sur son site." },
      { question: "Quelle assurance est obligatoire pour un serrurier ?", reponse: "La RC professionnelle est obligatoire pour couvrir les dommages causés lors des interventions. L'assurance décennale est requise uniquement pour les travaux affectant la structure du bâtiment (blindage de porte d'entrée, par exemple)." },
      { question: "La facturation Factur-X 2026 concerne-t-elle les serruriers ?", reponse: "Oui. Les serruriers doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, les TPE et PME devront émettre leurs factures aux clients professionnels au format électronique ; pour les particuliers, certaines données de vente seront transmises à l'administration (e-reporting)." },
    ],
    ["menuisier", "electricien", "plombier", "peintre"],
  ),

  // ── Services / Freelance ──
  metier("auto-entrepreneur", "Auto-entrepreneur", "service",
    ["facture auto entrepreneur", "modele facture micro entreprise"],
    ["Mention « TVA non applicable, art. 293 B du CGI » si franchise", "Numéro SIRET obligatoire", "Numérotation chronologique des factures"],
    [
      { question: "Comment faire une facture en auto-entrepreneur ?", reponse: "La facture doit comporter : vos coordonnées et SIRET, celles du client, la date, un numéro séquentiel, le détail des prestations, le montant HT, et la mention « TVA non applicable, art. 293 B du CGI » si vous êtes en franchise de TVA." },
      { question: "Un auto-entrepreneur doit-il facturer la TVA ?", reponse: "Non, tant que vous restez sous les seuils de franchise (36 800 € pour les services, 91 900 € pour la vente). Au-delà, vous devez facturer la TVA et la reverser." },
      { question: "Comment gérer les frais de déplacement en auto-entrepreneur ?", reponse: "Vous pouvez refacturer les frais de déplacement au client en les intégrant comme une ligne distincte sur la facture. En micro-entreprise, les frais ne sont pas déductibles : ils s'ajoutent à votre chiffre d'affaires déclaré." },
      { question: "Quelles sont les pénalités de retard obligatoires sur une facture auto-entrepreneur ?", reponse: "Toute facture doit mentionner le taux de pénalités de retard (minimum : taux BCE + 10 points) et l'indemnité forfaitaire de 40 € pour frais de recouvrement, conformément aux articles L441-10 et D441-5 du Code de commerce." },
      { question: "Un auto-entrepreneur est-il concerné par Factur-X 2026 ?", reponse: "Oui. Depuis le 1er septembre 2026, vous devez pouvoir recevoir des factures électroniques. À partir du 1er septembre 2027, vous devrez aussi émettre vos factures aux clients professionnels dans un format structuré (Factur-X, UBL ou CII), par une plateforme agréée, même en franchise de TVA." },
    ],
    ["consultant", "developpeur-freelance", "graphiste", "photographe"],
  ),
  metier("consultant", "Consultant", "service",
    ["facture consultant", "facture prestation conseil"],
    ["Conditions générales de vente recommandées", "Mentions obligatoires classiques"],
    [
      { question: "Comment facturer une prestation de conseil ?", reponse: "Précisez la nature de la mission, la période, le taux journalier ou le forfait, les frais éventuels (déplacement, hébergement) et les conditions de paiement." },
      { question: "Comment refacturer des frais de déplacement en tant que consultant ?", reponse: "Les frais de déplacement peuvent être refacturés au réel (sur justificatifs) ou au forfait. Créez une ligne séparée « Frais de déplacement » sur la facture, soumise au même taux de TVA que la prestation principale." },
      { question: "Quels sont les délais de paiement légaux pour une facture de consulting ?", reponse: "Le délai maximum est de 60 jours à compter de la date de facturation, ou 45 jours fin de mois (article L441-10 du Code de commerce). Les pénalités de retard et l'indemnité forfaitaire de 40 € doivent figurer sur la facture." },
      { question: "Un consultant doit-il facturer la TVA ?", reponse: "Oui, sauf en franchise de TVA (seuil de 36 800 € pour les prestations de services). Au-delà, le consultant collecte la TVA à 20 % et la reverse à l'État. Pour les clients étrangers (UE), l'autoliquidation peut s'appliquer." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un consultant ?", reponse: "Depuis le 1er septembre 2026, les consultants doivent pouvoir recevoir des factures électroniques. À partir du 1er septembre 2027, les TPE et PME devront émettre leurs factures aux clients professionnels français dans un format structuré, par une plateforme agréée. Cette obligation vise à automatiser les contrôles fiscaux et à réduire la fraude à la TVA." },
    ],
    ["auto-entrepreneur", "formateur", "coach", "developpeur-freelance"],
  ),
  metier("developpeur-freelance", "Développeur freelance", "service",
    ["facture developpeur", "facture freelance informatique"],
    ["Cession de droits d'auteur à préciser", "Conditions de maintenance et support"],
    [
      { question: "Comment facturer une prestation de développement ?", reponse: "Détaillez les livrables (site web, application, API), le volume (jours/homme ou forfait), la cession de droits éventuelle, et les conditions de maintenance. Précisez si le code source est livré." },
      { question: "Comment facturer la cession de droits d'auteur sur un logiciel ?", reponse: "La cession de droits sur le code source doit faire l'objet d'une ligne distincte sur la facture (article L131-3 du CPI). Précisez l'étendue (droits patrimoniaux cédés), la durée, le territoire et les supports autorisés." },
      { question: "Un développeur freelance doit-il facturer la TVA ?", reponse: "Oui, sauf en franchise de TVA (seuil de 36 800 € pour les services). Pour les clients dans l'UE, la TVA est autoliquidée par le client (mention obligatoire du numéro de TVA intracommunautaire sur la facture)." },
      { question: "Comment gérer les acomptes sur un projet de développement ?", reponse: "Émettez une facture d'acompte (30 à 50 % du montant total est courant) avant le démarrage, puis une facture de solde à la livraison. Chaque facture d'acompte doit comporter un numéro séquentiel et les mentions légales complètes." },
      { question: "Quelles obligations Factur-X 2026 pour un développeur freelance ?", reponse: "Les développeurs freelances doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026, et devront émettre leurs factures B2B dans un format structuré à partir du 1er septembre 2027. Qonforme joint déjà un fichier XML Factur-X au PDF de vos factures ; l'envoi par une plateforme agréée est en préparation." },
    ],
    ["graphiste", "consultant", "community-manager", "auto-entrepreneur"],
  ),
  metier("graphiste", "Graphiste", "service",
    ["facture graphiste", "devis creation graphique"],
    ["Cession de droits d'exploitation à détailler", "Nombre de révisions à préciser"],
    [
      { question: "Comment facturer une création graphique ?", reponse: "Séparez la création (recherche, conception, déclinaisons) de la cession de droits (exclusifs ou non, durée, supports). Précisez le nombre de propositions et de révisions incluses." },
      { question: "Comment facturer la cession de droits d'exploitation en graphisme ?", reponse: "La cession de droits doit être détaillée sur la facture conformément à l'article L131-3 du Code de la propriété intellectuelle : nature des droits cédés, étendue (supports, territoire), durée et rémunération distincte de la prestation créative." },
      { question: "Un graphiste freelance doit-il facturer la TVA ?", reponse: "Oui, sauf en franchise de TVA (seuil de 36 800 €). La TVA applicable est de 20 % sur les prestations de création graphique. Pour les clients dans l'UE assujettis, la TVA est autoliquidée par le client." },
      { question: "Comment gérer les frais d'achat (typos, images) sur une facture de graphiste ?", reponse: "Les achats de typographies, images stock ou impressions réalisés pour le compte du client peuvent être refacturés sur une ligne séparée avec le même taux de TVA. Conservez les justificatifs pour votre comptabilité." },
      { question: "Quelles obligations Factur-X 2026 pour un graphiste ?", reponse: "Les graphistes doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, ils devront émettre leurs factures aux clients professionnels dans un format structuré, et transmettre par e-reporting les données des ventes aux particuliers et aux clients étrangers." },
    ],
    ["photographe", "developpeur-freelance", "community-manager", "auto-entrepreneur"],
  ),
  metier("photographe", "Photographe", "service",
    ["facture photographe", "devis reportage photo"],
    ["Droits d'auteur et cession de droits à préciser", "TVA à 10% sur certaines prestations artistiques"],
    [
      { question: "Comment facturer un reportage photo ?", reponse: "Distinguez la prise de vue (tarif journée/demi-journée), le post-traitement (retouches, sélection), la cession de droits (usage, durée, supports) et les frais (déplacement, matériel spécifique)." },
      { question: "Quel taux de TVA pour un photographe ?", reponse: "Le taux standard de 20 % s'applique à la majorité des prestations photo. Cependant, les cessions de droits d'auteur sur des œuvres originales peuvent bénéficier du taux réduit de 10 % (article 278-0 bis du CGI) si le photographe est auteur." },
      { question: "Comment facturer la cession de droits sur des photos ?", reponse: "La cession de droits doit être une ligne séparée précisant : les droits cédés (reproduction, diffusion), les supports (web, print, affichage), le territoire, la durée et l'exclusivité éventuelle, conformément à l'article L131-3 du CPI." },
      { question: "Un photographe auto-entrepreneur doit-il facturer la TVA ?", reponse: "Non, tant qu'il reste sous le seuil de franchise de TVA (36 800 € pour les prestations de services). La mention « TVA non applicable, art. 293 B du CGI » doit figurer sur chaque facture. Au-delà du seuil, la TVA est obligatoire." },
      { question: "Quelles obligations Factur-X 2026 pour un photographe ?", reponse: "Les photographes doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, ils devront émettre au format électronique leurs factures aux clients professionnels : reportages corporate, événementiels et toute prestation facturée à une entreprise." },
    ],
    ["graphiste", "community-manager", "auto-entrepreneur", "traducteur"],
  ),
  metier("formateur", "Formateur", "service",
    ["facture formation", "convention de formation"],
    ["Convention de formation obligatoire", "Numéro de déclaration d'activité (NDA)", "Exonération de TVA possible (art. 261-4-4° du CGI)"],
    [
      { question: "Un formateur doit-il facturer la TVA ?", reponse: "Les organismes de formation peuvent être exonérés de TVA (article 261-4-4° du CGI) en obtenant une attestation auprès de la DREETS. Cette exonération doit être mentionnée sur les factures." },
      { question: "Quelles mentions obligatoires sur une facture de formation ?", reponse: "En plus des mentions légales classiques, une facture de formation doit mentionner le numéro de déclaration d'activité (NDA), l'intitulé de la formation, les dates, la durée en heures, le nombre de stagiaires et le lieu." },
      { question: "Comment facturer une formation financée par un OPCO ?", reponse: "Facturez l'OPCO directement (subrogation de paiement) ou le client qui se fait rembourser. La convention de formation tripartite doit être signée avant le début. Les OPCO exigent souvent un numéro de certification Qualiopi." },
      { question: "Comment gérer les frais annexes sur une facture de formation ?", reponse: "Les frais de déplacement, d'hébergement et de restauration du formateur peuvent être refacturés au réel ou au forfait. Créez des lignes distinctes sur la facture pour séparer les honoraires pédagogiques des frais annexes." },
      { question: "Quelles obligations Factur-X 2026 pour un formateur indépendant ?", reponse: "Les formateurs doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. L'émission au format structuré concernera les TPE et PME à partir du 1er septembre 2027, pour leurs factures aux clients professionnels. Si vos formations sont exonérées de TVA, vérifiez avec votre expert-comptable comment la réforme s'applique à ces opérations." },
    ],
    ["consultant", "coach", "auto-entrepreneur", "traducteur"],
  ),
  metier("coach", "Coach professionnel", "service",
    ["facture coaching", "devis accompagnement"],
    ["Mentions obligatoires classiques", "CGV recommandées"],
    [
      { question: "Comment facturer une séance de coaching ?", reponse: "Facturez à la séance ou au forfait (pack de séances). Précisez la durée, le lieu (présentiel/visio), et les conditions d'annulation." },
      { question: "Un coach professionnel doit-il facturer la TVA ?", reponse: "Oui, les prestations de coaching sont soumises à la TVA au taux de 20 %, sauf si le coach bénéficie de la franchise en base de TVA (seuil de 36 800 € de CA annuel, article 293 B du CGI)." },
      { question: "Comment facturer un pack de séances de coaching ?", reponse: "Émettez une facture pour le pack complet avec le détail : nombre de séances, durée unitaire, prix unitaire et prix total du pack. Si le paiement est échelonné, émettez une facture d'acompte puis une facture de solde." },
      { question: "Quels délais de paiement appliquer pour du coaching ?", reponse: "Le délai légal maximum est de 60 jours date de facture ou 45 jours fin de mois (article L441-10 du Code de commerce). En pratique, beaucoup de coachs facturent avant la prestation ou au comptant pour sécuriser leur trésorerie." },
      { question: "Quelles obligations Factur-X 2026 pour un coach ?", reponse: "Les coachs doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, ceux qui facturent des entreprises devront émettre ces factures au format électronique : coaching de dirigeant, coaching d'équipe et toute prestation B2B." },
    ],
    ["formateur", "consultant", "community-manager", "auto-entrepreneur"],
  ),
  metier("community-manager", "Community manager", "service",
    ["facture community management", "devis gestion reseaux sociaux"],
    ["Mentions obligatoires classiques", "Périmètre de la mission à détailler"],
    [
      { question: "Comment facturer du community management ?", reponse: "Facturez au forfait mensuel en détaillant : nombre de publications par réseau, création de contenu (visuels, vidéos), modération, reporting. Précisez les réseaux concernés." },
      { question: "Comment facturer les frais publicitaires (ads) en community management ?", reponse: "Les budgets publicitaires avancés pour le client doivent être refacturés sur une ligne séparée (débours ou refacturation de frais). Précisez si vous facturez un pourcentage de gestion en sus du budget média dépensé." },
      { question: "Un community manager freelance doit-il facturer la TVA ?", reponse: "Oui, au taux de 20 %, sauf en franchise de TVA (seuil de 36 800 € de CA annuel). Pour les clients dans l'UE, la TVA est autoliquidée. Mentionnez le numéro de TVA intracommunautaire du client sur la facture." },
      { question: "Comment protéger sa propriété intellectuelle en community management ?", reponse: "Les visuels et textes créés restent la propriété du community manager jusqu'à cession explicite. Précisez dans vos CGV et sur la facture si les droits d'exploitation sont cédés au client ou s'il dispose d'une simple licence d'utilisation." },
      { question: "Quelles obligations Factur-X 2026 pour un community manager ?", reponse: "Les community managers doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, leurs factures aux entreprises devront partir dans un format structuré (Factur-X, UBL ou CII), forfaits mensuels compris." },
    ],
    ["graphiste", "developpeur-freelance", "photographe", "consultant"],
  ),
  metier("traducteur", "Traducteur", "service",
    ["facture traduction", "devis traduction"],
    ["Cession de droits si traduction littéraire", "Tarif au mot ou au feuillet"],
    [
      { question: "Comment facturer une traduction ?", reponse: "Facturez au mot (tarif standard en traduction technique) ou au feuillet (1 500 signes espaces comprises). Précisez les langues, le domaine de spécialité et le délai de livraison." },
      { question: "Comment facturer la cession de droits sur une traduction littéraire ?", reponse: "Pour les traductions littéraires, la cession de droits d'auteur doit être détaillée conformément à l'article L131-3 du CPI : étendue des droits, durée, territoire et supports. La rémunération de la cession doit être distincte des honoraires de traduction." },
      { question: "Un traducteur freelance doit-il facturer la TVA ?", reponse: "Oui, au taux de 20 %, sauf en franchise de TVA (seuil de 36 800 €). Pour les clients professionnels dans l'UE, la TVA est autoliquidée par le client. Pensez à vérifier et mentionner le numéro de TVA intracommunautaire." },
      { question: "Comment gérer les pénalités de retard sur une facture de traduction ?", reponse: "La facture doit mentionner le taux de pénalités de retard applicable (minimum : taux directeur BCE + 10 points) et l'indemnité forfaitaire de 40 € pour frais de recouvrement, conformément à l'article L441-10 du Code de commerce." },
      { question: "Quelles obligations Factur-X 2026 pour un traducteur ?", reponse: "Les traducteurs doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, ils devront émettre au format électronique leurs factures aux clients professionnels français. Pour les clients étrangers, les données de transaction seront transmises à l'administration fiscale (e-reporting)." },
    ],
    ["formateur", "consultant", "graphiste", "auto-entrepreneur"],
  ),

  // ── Artisanat / Commerce ──
  metier("coiffeur", "Coiffeur", "artisanat",
    ["facture salon coiffure", "logiciel caisse coiffeur"],
    ["Affichage des prix obligatoire", "Note/facture obligatoire au-delà de 25 €"],
    [
      { question: "Un coiffeur doit-il faire des factures ?", reponse: "Une note (ticket) suffit pour les particuliers si le montant est inférieur à 25 €. Au-delà, une note détaillée est obligatoire. Pour les clients professionnels, une facture complète est toujours requise." },
      { question: "Quel taux de TVA pour un salon de coiffure ?", reponse: "Le taux de TVA est de 20 % pour l'ensemble des prestations de coiffure (coupes, colorations, soins). La vente de produits capillaires est également soumise au taux de 20 %. Il n'existe pas de taux réduit pour la coiffure." },
      { question: "Un coiffeur doit-il afficher ses prix ?", reponse: "Oui, l'affichage des prix TTC est obligatoire (arrêté du 27 mars 1987). Les tarifs doivent être visibles de l'extérieur pour les prestations courantes et à l'intérieur pour l'ensemble des prestations, hommes et femmes séparément." },
      { question: "Comment facturer la vente de produits en salon de coiffure ?", reponse: "La vente de produits (shampoings, soins, accessoires) doit apparaître sur une ligne distincte de la prestation de coiffure. Le taux de TVA est identique (20 %) mais la distinction facilite le suivi comptable et la gestion des stocks." },
      { question: "Quelles obligations Factur-X 2026 pour un coiffeur ?", reponse: "Les coiffeurs doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, les factures aux clients professionnels (contrats entreprise, spectacles) devront être émises au format électronique, et les données des ventes aux particuliers transmises à l'administration fiscale (e-reporting)." },
    ],
    ["estheticienne", "auto-entrepreneur", "fleuriste", "traiteur"],
  ),
  metier("estheticienne", "Esthéticienne", "artisanat",
    ["facture institut beaute", "logiciel facturation esthetique"],
    ["Affichage des prix obligatoire", "Note/facture obligatoire"],
    [
      { question: "Comment facturer des soins esthétiques ?", reponse: "Détaillez chaque prestation (soin visage, épilation, manucure) avec son prix unitaire. Pour les forfaits et cartes prépayées, précisez la validité et les conditions d'utilisation." },
      { question: "Quel taux de TVA pour un institut de beauté ?", reponse: "Le taux de TVA est de 20 % pour l'ensemble des prestations esthétiques (soins, épilations, manucures, maquillage). La revente de produits cosmétiques est également soumise au taux normal de 20 %." },
      { question: "À partir de quel montant une esthéticienne doit-elle délivrer une note ?", reponse: "Une note détaillée est obligatoire dès que le montant dépasse 25 € TTC pour un client particulier (arrêté du 3 octobre 1983). En dessous, la remise d'une note reste recommandée mais n'est pas obligatoire." },
      { question: "Comment gérer les cartes prépayées et abonnements en institut ?", reponse: "Émettez une facture lors de la vente de la carte ou de l'abonnement. Le chiffre d'affaires est comptabilisé au fur et à mesure de l'utilisation des séances (produit constaté d'avance). Précisez la durée de validité et les conditions de remboursement." },
      { question: "Quelles obligations Factur-X 2026 pour une esthéticienne ?", reponse: "Les esthéticiennes doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, leurs factures aux entreprises (comités d'entreprise, hôtels, spas) devront être émises au format électronique ; les ventes aux particuliers relèveront du e-reporting." },
    ],
    ["coiffeur", "auto-entrepreneur", "fleuriste", "dieteticien"],
  ),
  metier("paysagiste", "Paysagiste", "btp",
    ["facture entretien jardin", "devis amenagement paysager"],
    ["Devis obligatoire pour travaux > 150 €", "Assurance RC professionnelle"],
    [
      { question: "Comment facturer un entretien de jardin ?", reponse: "Facturez à l'heure ou au forfait. Détaillez : tonte, taille, désherbage, évacuation des déchets verts. Pour les particuliers, le crédit d'impôt SAP (50%) s'applique à l'entretien courant." },
      { question: "Quel taux de TVA pour des travaux de paysagisme ?", reponse: "Le taux de 20 % s'applique aux travaux de création (aménagement, plantation, terrassement). Le taux de 10 % peut s'appliquer à l'entretien de jardins attenants à un logement de plus de 2 ans. Les prestations SAP d'entretien courant sont à 20 %." },
      { question: "Un paysagiste doit-il souscrire une assurance décennale ?", reponse: "L'assurance décennale est obligatoire pour les ouvrages paysagers structurels (murs de soutènement, terrasses, allées carrossables). Pour l'entretien et les plantations, la RC professionnelle suffit généralement." },
      { question: "Comment facturer un contrat d'entretien annuel de jardin ?", reponse: "Proposez un forfait annuel avec un calendrier d'interventions (mensuel ou trimestriel). Détaillez les prestations incluses (tonte, taille, traitement) et émettez une facture par passage ou une facture mensuelle selon l'accord." },
      { question: "Un paysagiste est-il concerné par Factur-X 2026 ?", reponse: "Oui. Les paysagistes doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, ils devront émettre au format électronique leurs factures aux entreprises ; le e-reporting s'appliquera aux prestations pour les particuliers." },
    ],
    ["macon", "menuisier", "carreleur", "fleuriste"],
  ),
  metier("architecte-interieur", "Architecte d'intérieur", "service",
    ["facture architecte interieur", "devis decoration interieure", "honoraires architecte"],
    ["Barème d'honoraires à communiquer", "Assurance RC professionnelle"],
    [
      { question: "Comment facturer des honoraires d'architecte d'intérieur ?", reponse: "Facturez au pourcentage du montant des travaux (8-15%), au forfait, ou en régie (taux horaire/journalier). Détaillez les phases : étude, conception, plans, suivi de chantier." },
      { question: "Un architecte d'intérieur doit-il facturer la TVA ?", reponse: "Oui, les honoraires d'architecte d'intérieur sont soumis à la TVA au taux de 20 %. En franchise de TVA (seuil 36 800 €), mentionnez « TVA non applicable, art. 293 B du CGI ». Les achats de mobilier refacturés suivent leur propre taux." },
      { question: "Comment refacturer les achats de mobilier et matériaux ?", reponse: "Deux options : la refacturation (vous achetez et revendez avec marge, TVA sur le tout) ou le débours (vous achetez au nom du client, aucune TVA sur le remboursement). La méthode choisie doit être claire dans le contrat et sur la facture." },
      { question: "Quelles pénalités de retard mentionner sur une facture d'architecte d'intérieur ?", reponse: "La facture doit indiquer le taux de pénalités de retard (minimum : taux directeur BCE + 10 points) et l'indemnité forfaitaire de 40 € pour frais de recouvrement, conformément aux articles L441-10 et D441-5 du Code de commerce." },
      { question: "Quelles obligations Factur-X 2026 pour un architecte d'intérieur ?", reponse: "Les architectes d'intérieur doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, leurs factures aux clients professionnels devront être émises au format électronique : honoraires de conception, de suivi de chantier et achats refacturés." },
    ],
    ["peintre", "menuisier", "carreleur", "graphiste"],
  ),
  metier("traiteur", "Traiteur", "artisanat",
    ["facture traiteur", "devis reception traiteur"],
    ["Respect des normes HACCP", "Devis détaillé avec menu"],
    [
      { question: "Comment établir un devis de traiteur ?", reponse: "Détaillez : nombre de convives, menu (entrée, plat, dessert, boissons), formule (buffet, assis), matériel (vaisselle, nappes), personnel de service, livraison et installation." },
      { question: "Quel taux de TVA pour un traiteur ?", reponse: "Le taux de 10 % s'applique aux prestations de traiteur avec consommation immédiate (livraison de plateaux-repas, buffets). Le taux de 5,5 % s'applique aux produits alimentaires vendus à emporter sans service. Le taux de 20 % concerne les boissons alcoolisées." },
      { question: "Un traiteur doit-il faire un devis ou une facture ?", reponse: "Un devis détaillé est obligatoire pour toute prestation événementielle. Après l'événement, une facture complète doit être émise avec les mentions légales, le détail des prestations réellement fournies et les éventuels suppléments." },
      { question: "Comment gérer les acomptes pour une prestation traiteur ?", reponse: "Il est courant de demander un acompte de 30 à 50 % à la commande. Émettez une facture d'acompte avec numéro séquentiel, puis une facture de solde après l'événement. La facture de solde doit déduire l'acompte déjà versé." },
      { question: "Quelles obligations Factur-X 2026 pour un traiteur ?", reponse: "Les traiteurs doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, leurs factures aux entreprises devront être émises au format électronique ; les prestations aux particuliers relèveront du e-reporting." },
    ],
    ["fleuriste", "photographe", "coiffeur", "auto-entrepreneur"],
  ),
  metier("fleuriste", "Fleuriste", "artisanat",
    ["facture fleuriste", "logiciel caisse fleuriste"],
    ["Affichage des prix obligatoire", "TVA à 10% sur certaines plantes"],
    [
      { question: "Quel taux de TVA pour un fleuriste ?", reponse: "Le taux de TVA est de 10% pour les fleurs coupées, plantes vivantes et compositions florales. Le taux de 20% s'applique aux accessoires et contenants décoratifs." },
      { question: "Un fleuriste doit-il faire une facture ou une note ?", reponse: "Pour les particuliers, une note (ticket de caisse) suffit en dessous de 25 € TTC. Au-delà, une note détaillée est obligatoire. Pour les clients professionnels (entreprises, hôtels, événementiel), une facture complète est toujours requise." },
      { question: "Comment afficher les prix en boutique de fleurs ?", reponse: "L'affichage des prix TTC est obligatoire pour chaque produit proposé à la vente (arrêté du 3 décembre 1987). Pour les compositions sur mesure, affichez un prix indicatif au budget ou le prix à la tige pour les principales variétés." },
      { question: "Comment facturer des prestations de décoration florale événementielle ?", reponse: "Établissez un devis détaillant : les compositions (nombre, taille, variétés), la livraison, l'installation, le démontage éventuel et la location de vases/structures. Facturez un acompte de 30 à 50 % à la commande." },
      { question: "Quelles obligations Factur-X 2026 pour un fleuriste ?", reponse: "Les fleuristes doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, leurs factures aux clients professionnels (entreprises, hôtels) devront être émises au format électronique, et les données des ventes aux particuliers transmises à l'administration." },
    ],
    ["traiteur", "coiffeur", "estheticienne", "auto-entrepreneur"],
  ),

  // ── Santé ──
  metier("osteopathe", "Ostéopathe", "sante",
    ["facture osteopathe", "note honoraires osteopathie"],
    ["Note d'honoraires obligatoire", "Exonération de TVA (art. 261-4-1° du CGI)", "Numéro ADELI ou RPPS"],
    [
      { question: "Un ostéopathe doit-il facturer la TVA ?", reponse: "Non, les actes d'ostéopathie sont exonérés de TVA en vertu de l'article 261-4-1° du CGI. La mention « TVA non applicable, art. 261-4-1° du CGI » doit figurer sur les notes d'honoraires." },
      { question: "Quelle différence entre note d'honoraires et facture pour un ostéopathe ?", reponse: "La note d'honoraires est le document émis par les professions libérales de santé. Elle contient les mêmes mentions obligatoires qu'une facture (identité, date, montant, numéro séquentiel) mais porte la dénomination « note d'honoraires »." },
      { question: "Un ostéopathe doit-il mentionner son numéro ADELI ou RPPS ?", reponse: "Oui, le numéro ADELI (ou RPPS selon l'enregistrement) doit figurer sur les notes d'honoraires. Ce numéro atteste de l'inscription au registre des professionnels de santé et permet le remboursement par les mutuelles." },
      { question: "Comment facturer un patient pour le remboursement par la mutuelle ?", reponse: "Émettez une note d'honoraires détaillée avec votre numéro ADELI/RPPS, la nature de l'acte (« consultation d'ostéopathie »), la date et le montant. La plupart des mutuelles exigent ce document pour rembourser leurs assurés." },
      { question: "La facturation électronique Factur-X concerne-t-elle les ostéopathes ?", reponse: "Comme toute entreprise assujettie à la TVA, un ostéopathe doit pouvoir recevoir des factures électroniques depuis le 1er septembre 2026, par exemple celles de ses fournisseurs. Pour l'émission, prévue au 1er septembre 2027 pour les TPE, les actes exonérés de TVA obéissent à des règles particulières : faites le point avec votre expert-comptable, notamment pour les séances facturées à des entreprises ou à des clubs sportifs." },
    ],
    ["kinesitherapeute", "dieteticien", "infirmier-liberal", "coach"],
  ),
  metier("kinesitherapeute", "Kinésithérapeute", "sante",
    ["facture kine", "note honoraires kinesitherapie"],
    ["Feuille de soins pour les actes remboursés", "Exonération de TVA (art. 261-4-1° du CGI)", "Numéro RPPS obligatoire"],
    [
      { question: "Comment facturer en tant que kinésithérapeute libéral ?", reponse: "Pour les actes conventionnés, utilisez la feuille de soins (tiers payant ou remboursement patient). Pour les dépassements ou actes hors nomenclature, établissez une note d'honoraires séparée." },
      { question: "Un kinésithérapeute doit-il facturer la TVA ?", reponse: "Non, les actes de kinésithérapie sont exonérés de TVA en vertu de l'article 261-4-1° du CGI. Cette exonération couvre tous les actes thérapeutiques, y compris la rééducation et la balnéothérapie prescrites par un médecin." },
      { question: "Le numéro RPPS est-il obligatoire sur une note d'honoraires de kiné ?", reponse: "Oui, le numéro RPPS (Répertoire Partagé des Professionnels de Santé) doit figurer sur toutes les notes d'honoraires et feuilles de soins. Il remplace progressivement le numéro ADELI pour les kinésithérapeutes." },
      { question: "Comment facturer des séances de kiné en tiers payant ?", reponse: "En tiers payant, la part Sécurité sociale est facturée directement à la CPAM via le système Sesam-Vitale. Seul le reste à charge (ticket modérateur) est facturé au patient, sauf si la mutuelle pratique aussi le tiers payant complémentaire." },
      { question: "Un kiné peut-il facturer des actes hors nomenclature ?", reponse: "Oui, les actes hors nomenclature (kiné du sport, drainage esthétique, bien-être) sont facturés librement via une note d'honoraires. Ces actes ne sont pas remboursés par la Sécurité sociale mais peuvent l'être par certaines mutuelles." },
    ],
    ["osteopathe", "infirmier-liberal", "dieteticien", "formateur"],
  ),
  metier("infirmier-liberal", "Infirmier libéral", "sante",
    ["facture infirmier liberal", "facturation soins infirmiers"],
    ["Facturation Sesam-Vitale", "Exonération de TVA (art. 261-4-1° du CGI)", "Numéro RPPS"],
    [
      { question: "Comment facturer les soins infirmiers à domicile ?", reponse: "Les soins infirmiers conventionnés sont facturés via le système Sesam-Vitale (tiers payant). Les majorations (nuit, dimanche, urgence, déplacement) sont codifiées. Les soins hors nomenclature sont facturés librement." },
      { question: "Les soins infirmiers sont-ils exonérés de TVA ?", reponse: "Oui, les actes de soins infirmiers sont exonérés de TVA en vertu de l'article 261-4-1° du CGI. Cette exonération s'applique à tous les actes thérapeutiques réalisés par un infirmier diplômé d'État, qu'ils soient conventionnés ou non." },
      { question: "Le numéro RPPS est-il obligatoire pour un infirmier libéral ?", reponse: "Oui, le numéro RPPS doit figurer sur toutes les feuilles de soins et notes d'honoraires. Il est indispensable pour la télétransmission Sesam-Vitale et l'identification auprès de la CPAM et des organismes complémentaires." },
      { question: "Comment facturer les indemnités de déplacement en soins infirmiers ?", reponse: "Les indemnités forfaitaires de déplacement (IFD) et les indemnités kilométriques (IK) sont codifiées par la convention nationale. Elles s'ajoutent automatiquement aux actes lors de la télétransmission via Sesam-Vitale." },
      { question: "Un infirmier libéral est-il concerné par Factur-X 2026 ?", reponse: "Pour les actes conventionnés aux particuliers, la facturation passe par Sesam-Vitale. Comme toute entreprise assujettie à la TVA, un infirmier libéral doit pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. Pour les prestations facturées à des établissements (médecine du travail, EHPAD), faites le point avec votre expert-comptable : les actes exonérés de TVA obéissent à des règles particulières." },
    ],
    ["kinesitherapeute", "osteopathe", "dieteticien", "auto-entrepreneur"],
  ),
  metier("dieteticien", "Diététicien", "sante",
    ["facture dieteticien", "note honoraires nutrition"],
    ["Exonération de TVA des actes paramédicaux (art. 261-4-1° du CGI)", "Numéro ADELI"],
    [
      { question: "Les consultations diététiques sont-elles soumises à la TVA ?", reponse: "Non, les consultations diététiques réalisées par un diététicien diplômé sont exonérées de TVA. Utilisez la mention « TVA non applicable, art. 261-4-1° du CGI »." },
      { question: "Un diététicien doit-il émettre une note d'honoraires ou une facture ?", reponse: "Le diététicien émet une note d'honoraires pour ses consultations individuelles. Ce document doit comporter les mentions légales classiques (identité, SIRET, date, numéro, montant) ainsi que le numéro ADELI du praticien." },
      { question: "Le numéro ADELI est-il obligatoire pour un diététicien ?", reponse: "Oui, tout diététicien doit être enregistré au fichier ADELI auprès de l'ARS. Ce numéro doit figurer sur les notes d'honoraires et permet aux patients de demander un remboursement auprès de leur mutuelle." },
      { question: "Les consultations diététiques sont-elles remboursées ?", reponse: "Les consultations diététiques ne sont pas remboursées par la Sécurité sociale (sauf dans le cadre du dispositif « Mon bilan diététique » pour les jeunes). Certaines mutuelles proposent un forfait annuel. La note d'honoraires est indispensable pour le remboursement." },
      { question: "La facturation Factur-X 2026 concerne-t-elle les diététiciens ?", reponse: "Comme toute entreprise assujettie à la TVA, un diététicien doit pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. Pour les prestations facturées à des entreprises ou à des établissements (EHPAD, cliniques, cantines), faites le point avec votre expert-comptable : les consultations exonérées de TVA obéissent à des règles particulières." },
    ],
    ["osteopathe", "kinesitherapeute", "infirmier-liberal", "coach"],
  ),

  // ── Services professionnels ──
  metier("comptable", "Comptable / Expert-comptable", "service",
    ["facture cabinet comptable", "honoraires expert comptable"],
    ["Secret professionnel", "Assurance RC pro", "Respect du Code de déontologie OEC"],
    [
      { question: "Comment facturer les honoraires d'un cabinet comptable ?", reponse: "Les honoraires doivent être détaillés par type de mission (tenue comptable, bilan annuel, conseil) conformément à la lettre de mission obligatoire (article 151 du Code de déontologie OEC). La facturation peut être au forfait ou au temps passé." },
      { question: "Un expert-comptable doit-il facturer la TVA sur ses honoraires ?", reponse: "Oui, les honoraires d'expertise comptable sont soumis à la TVA au taux normal de 20 %. La franchise en base (article 293 B du CGI) est rarement applicable compte tenu du niveau de chiffre d'affaires habituel des cabinets." },
      { question: "La facturation électronique est-elle obligatoire pour un expert-comptable ?", reponse: "Oui. Un cabinet comptable doit pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. Il devra émettre ses factures aux clients professionnels dans un format structuré, par une plateforme agréée, à partir du 1er septembre 2027 s'il est une TPE ou une PME (depuis le 1er septembre 2026 pour les grandes entreprises et les ETI)." },
      { question: "Comment rédiger une lettre de mission pour la facturation comptable ?", reponse: "La lettre de mission est obligatoire (article 151 du Code de déontologie OEC) et doit préciser la nature des travaux, les honoraires, les délais, les responsabilités respectives et les conditions de résiliation. Elle sert de base à la facturation." },
      { question: "Peut-on exporter un FEC depuis Qonforme ?", reponse: "Oui. Qonforme exporte vos factures et vos avoirs au format FEC (Fichier des écritures comptables) : journal des ventes et journal des avoirs, prêts à être importés dans le logiciel comptable du cabinet." },
    ],
    ["consultant", "formateur", "auto-entrepreneur", "avocat"],
  ),
  metier("avocat", "Avocat", "service",
    ["facture avocat", "honoraires avocat", "note honoraires avocat"],
    ["Convention d'honoraires obligatoire (> 10 000 €)", "Secret professionnel", "TVA 20 % sur honoraires"],
    [
      { question: "La convention d'honoraires est-elle obligatoire pour un avocat ?", reponse: "Oui, la convention d'honoraires est obligatoire pour toute mission dont le montant prévisible dépasse 10 000 € HT (article 10 de la loi n° 71-1130). Elle doit détailler le mode de calcul des honoraires (forfait, taux horaire, honoraire de résultat)." },
      { question: "Un avocat doit-il facturer la TVA sur ses honoraires ?", reponse: "Oui, les honoraires d'avocat sont soumis à la TVA au taux de 20 % (article 256 du CGI). La franchise en base (article 293 B) est possible sous le seuil de 36 800 € de CA annuel, mais concerne principalement les avocats débutants." },
      { question: "Comment facturer une provision sur honoraires (retainer) ?", reponse: "La provision est facturée au début de la mission via une facture d'acompte. Elle doit transiter par le compte CARPA de l'avocat si elle est destinée à couvrir des frais de procédure. La facture de solde déduit la provision déjà versée." },
      { question: "Qu'est-ce que le compte CARPA et quel impact sur la facturation ?", reponse: "Le compte CARPA (Caisse des Règlements Pécuniaires des Avocats) reçoit les fonds destinés aux clients ou provenant d'eux. Les honoraires ne transitent pas par la CARPA : ils sont facturés directement et réglés sur le compte professionnel de l'avocat." },
      { question: "La facturation électronique Factur-X concerne-t-elle les avocats ?", reponse: "Oui. Les avocats doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, les cabinets qui sont des TPE ou des PME devront émettre leurs factures aux clients professionnels au format électronique, par une plateforme agréée." },
    ],
    ["comptable", "consultant", "formateur", "coach"],
  ),
  metier("agent-immobilier", "Agent immobilier", "service",
    ["facture agent immobilier", "commission immobiliere", "honoraires agence"],
    ["Carte professionnelle T obligatoire", "Garantie financière", "Affichage honoraires obligatoire"],
    [
      { question: "Comment facturer une commission d'agent immobilier ?", reponse: "La commission est facturée à la signature de l'acte authentique chez le notaire. Elle doit correspondre au barème affiché en agence et mentionné dans le mandat. La facture précise le bien concerné, le montant de la vente et le pourcentage de commission." },
      { question: "Quels types de mandats impactent la facturation immobilière ?", reponse: "Le mandat simple permet au vendeur de vendre par lui-même sans commission. Le mandat exclusif garantit la rémunération de l'agent. Le mandat semi-exclusif est un intermédiaire. Le type de mandat doit figurer sur le contrat et conditionne le droit à commission." },
      { question: "Un agent immobilier doit-il facturer la TVA ?", reponse: "Oui, les commissions d'agent immobilier sont soumises à la TVA au taux de 20 % (article 256 du CGI). L'agent doit afficher ses honoraires TTC en vitrine et sur les annonces conformément à l'arrêté du 10 janvier 2017." },
      { question: "L'affichage du barème d'honoraires est-il obligatoire ?", reponse: "Oui, l'arrêté du 10 janvier 2017 impose l'affichage visible des honoraires TTC en vitrine et sur chaque annonce. Le barème doit préciser si les honoraires sont à la charge de l'acquéreur ou du vendeur, et le mode de calcul (pourcentage ou forfait)." },
      { question: "La facturation Factur-X 2026 concerne-t-elle les agents immobiliers ?", reponse: "Oui. Les agents immobiliers doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, les TPE et PME devront émettre au format électronique leurs factures aux professionnels : les commissions facturées à des sociétés (promoteurs, marchands de biens) sont directement concernées." },
    ],
    ["architecte-interieur", "consultant", "photographe", "auto-entrepreneur"],
  ),

  // ── Artisanat / Commerce (suite) ──
  metier("boulanger", "Boulanger / Pâtissier", "artisanat",
    ["facture boulangerie", "logiciel caisse boulanger", "ticket boulangerie"],
    ["Affichage prix au kg obligatoire", "Normes HACCP", "TVA à 5,5 % sur le pain et les viennoiseries"],
    [
      { question: "Quels taux de TVA appliquer en boulangerie-pâtisserie ?", reponse: "Le pain et les viennoiseries de consommation courante sont à 5,5 % (article 278-0 bis du CGI). Les pâtisseries et confiseries sont à 10 % si consommées sur place, 5,5 % si emportées. Les boissons alcoolisées et produits de luxe sont à 20 %." },
      { question: "Un boulanger doit-il émettre un ticket ou une facture ?", reponse: "Pour les ventes aux particuliers, un ticket de caisse suffit (obligatoire si le client le demande ou si le montant dépasse 25 € TTC). Pour les clients professionnels (restaurants, collectivités), une facture complète est obligatoire." },
      { question: "Un logiciel de caisse certifié est-il obligatoire en boulangerie ?", reponse: "Oui, depuis le 1er janvier 2018, tout commerçant assujetti à la TVA utilisant un logiciel de caisse doit disposer d'un logiciel certifié NF 525 ou attesté conforme (article 286-I-3° bis du CGI), garantissant l'inaltérabilité et la conservation des données." },
      { question: "Comment gérer l'affichage des allergènes en boulangerie ?", reponse: "Le règlement européen INCO n° 1169/2011 impose l'information sur les 14 allergènes majeurs. En boulangerie, cette information doit être accessible sur le lieu de vente (affichage, classeur). La facture ou le ticket n'a pas à les mentionner." },
      { question: "La facturation électronique Factur-X concerne-t-elle les boulangers ?", reponse: "Oui. Les boulangers doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026, notamment celles de leurs fournisseurs. À partir du 1er septembre 2027, leurs factures aux clients professionnels (restaurants, hôtels) devront être émises au format électronique, et les données des ventes aux particuliers transmises à l'administration fiscale (e-reporting)." },
    ],
    ["traiteur", "fleuriste", "coiffeur", "auto-entrepreneur"],
  ),
  metier("vtc", "Chauffeur VTC", "service",
    ["facture vtc", "facturation chauffeur prive", "note course vtc"],
    ["Carte professionnelle VTC obligatoire", "Licence de transport", "Assurance RC exploitation"],
    [
      { question: "Comment facturer une course VTC ?", reponse: "La facture ou note de course doit mentionner la date, les lieux de prise en charge et de dépose, le kilométrage, la durée, le tarif appliqué et le montant total TTC. Pour les courses > 25 € avec un particulier, la remise d'une note est obligatoire." },
      { question: "Un chauffeur VTC doit-il facturer la TVA ?", reponse: "Oui, les prestations de transport VTC sont soumises à la TVA au taux de 10 % (article 279-b bis du CGI pour le transport de voyageurs). En franchise de TVA (article 293 B, seuil 36 800 €), mentionnez l'exonération sur la facture." },
      { question: "Quel statut juridique choisir pour facturer en VTC ?", reponse: "Le VTC peut exercer en auto-entrepreneur (micro-entreprise), SASU ou EURL. L'auto-entreprise est simple mais limitée en déduction de charges. La SASU permet de déduire les frais (véhicule, assurance, carburant) et de récupérer la TVA." },
      { question: "Comment déduire les frais de véhicule en tant que VTC ?", reponse: "En société, les frais de véhicule (leasing, carburant, entretien, assurance) sont déductibles du résultat fiscal. En auto-entreprise, aucune déduction n'est possible : les charges sont couvertes par l'abattement forfaitaire de 50 % sur le CA (BIC services)." },
      { question: "La facturation électronique Factur-X concerne-t-elle les VTC ?", reponse: "Oui. Les chauffeurs VTC doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, ceux qui facturent des entreprises (contrats corporate, événementiel) devront émettre ces factures au format électronique ; les courses facturées aux particuliers relèveront du e-reporting." },
    ],
    ["auto-entrepreneur", "consultant", "coach", "traducteur"],
  ),
  metier("femme-de-menage", "Femme de ménage / Nettoyage", "service",
    ["facture menage", "facture nettoyage", "facture aide menagere"],
    ["Convention collective du nettoyage", "Crédit d'impôt SAP 50%", "CESU si particulier employeur"],
    [
      { question: "Quelle différence entre CESU et facture pour le ménage ?", reponse: "Le CESU (Chèque Emploi Service Universel) est utilisé quand le particulier est employeur direct. Si vous exercez en tant qu'entreprise ou auto-entrepreneur, vous émettez une facture classique. Dans les deux cas, le client bénéficie du crédit d'impôt SAP de 50 %." },
      { question: "Comment bénéficier du crédit d'impôt services à la personne pour le ménage ?", reponse: "Le crédit d'impôt de 50 % (article 199 sexdecies du CGI) s'applique aux dépenses de ménage à domicile dans la limite de 12 000 €/an. L'entreprise de nettoyage doit être déclarée SAP auprès de la DREETS et mentionner l'attestation fiscale annuelle." },
      { question: "Quel taux de TVA pour les prestations de ménage ?", reponse: "Le taux de TVA est de 20 % pour les prestations de nettoyage professionnel (bureaux, locaux). Pour les services à la personne (ménage à domicile chez un particulier), le taux est de 10 % si l'entreprise est agréée SAP (article 279-i du CGI)." },
      { question: "Comment facturer des prestations de ménage à l'heure ?", reponse: "Précisez sur la facture le nombre d'heures, le tarif horaire TTC, les dates d'intervention et l'adresse du lieu de prestation. Pour les contrats récurrents, émettez une facture mensuelle récapitulative avec le détail de chaque passage." },
      { question: "La facturation Factur-X 2026 concerne-t-elle les entreprises de ménage ?", reponse: "Oui. Les entreprises de nettoyage doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, les TPE et PME devront émettre au format électronique leurs factures aux clients professionnels (bureaux, commerces) ; le e-reporting s'appliquera au ménage facturé aux particuliers." },
    ],
    ["paysagiste", "auto-entrepreneur", "coiffeur", "estheticienne"],
  ),
  metier("informaticien", "Informaticien / Réparateur", "service",
    ["facture reparation informatique", "devis depannage informatique", "facture maintenance"],
    ["Mentions obligatoires classiques", "Devis obligatoire > 150 €", "Garantie légale de conformité"],
    [
      { question: "Comment facturer une réparation informatique ?", reponse: "Détaillez le diagnostic, la main-d'œuvre (temps passé et tarif horaire), les pièces remplacées et les frais de déplacement éventuels. Le devis est obligatoire si le montant dépasse 150 € TTC (article L111-3 du Code de la consommation)." },
      { question: "Un devis est-il obligatoire pour un dépannage informatique ?", reponse: "Oui, un devis détaillé est obligatoire avant toute intervention dont le montant dépasse 150 € TTC (arrêté du 24 janvier 2017). Le devis doit préciser le diagnostic, les opérations prévues, les pièces à remplacer et le coût total." },
      { question: "Quelle garantie s'applique après une réparation informatique ?", reponse: "La garantie légale de conformité (articles L217-4 à L217-14 du Code de la consommation) s'applique aux pièces neuves installées pendant 2 ans. Pour la main-d'œuvre, une garantie commerciale de 3 à 6 mois est courante dans la profession." },
      { question: "Un réparateur informatique est-il responsable des données du client ?", reponse: "Le réparateur a une obligation de moyens concernant la préservation des données. Il doit informer le client du risque de perte de données avant l'intervention et obtenir son accord écrit. Une clause de non-responsabilité dans les CGV est fortement recommandée." },
      { question: "La facturation Factur-X 2026 concerne-t-elle les réparateurs informatiques ?", reponse: "Oui. Les réparateurs informatiques doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, leurs factures aux clients professionnels, contrats de maintenance compris, devront être émises au format électronique." },
    ],
    ["developpeur-freelance", "consultant", "auto-entrepreneur", "community-manager"],
  ),
  metier("jardinier", "Jardinier", "artisanat",
    ["facture jardinage", "devis entretien jardin", "facture tonte pelouse"],
    ["Crédit d'impôt SAP 50%", "Assurance RC pro", "Devis obligatoire > 150 €"],
    [
      { question: "Le crédit d'impôt services à la personne s'applique-t-il au jardinage ?", reponse: "Oui, les petits travaux de jardinage (tonte, taille de haies, désherbage) ouvrent droit au crédit d'impôt de 50 % dans la limite de 5 000 €/an (article 199 sexdecies du CGI). L'entreprise doit être déclarée SAP et fournir une attestation fiscale annuelle au client." },
      { question: "Quel taux de TVA pour des travaux de jardinage ?", reponse: "Le taux de 20 % s'applique aux travaux de création (aménagement, plantation, engazonnement). Le taux de 10 % peut s'appliquer à l'entretien de jardins attenants à un logement de plus de 2 ans. Les prestations SAP de petits travaux de jardinage restent à 20 %." },
      { question: "Un jardinier peut-il utiliser le CESU ?", reponse: "Oui, si le jardinier est employé directement par un particulier (emploi direct), le CESU simplifie les formalités. En revanche, si le jardinier exerce en entreprise ou auto-entreprise, il émet des factures classiques et le client bénéficie du crédit d'impôt SAP." },
      { question: "Comment facturer un contrat d'entretien saisonnier de jardin ?", reponse: "Proposez un forfait annuel ou saisonnier avec un planning d'interventions. Détaillez les prestations incluses (tonte, taille, ramassage feuilles, traitement) et émettez une facture mensuelle ou trimestrielle selon l'accord convenu avec le client." },
      { question: "La facturation Factur-X 2026 concerne-t-elle les jardiniers ?", reponse: "Oui. Les jardiniers doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, leurs factures aux entreprises devront être émises au format électronique ; le e-reporting s'appliquera aux prestations de jardinage facturées aux particuliers." },
    ],
    ["paysagiste", "femme-de-menage", "auto-entrepreneur", "fleuriste"],
  ),
  metier("demenageur", "Déménageur", "service",
    ["facture demenagement", "devis demenageur", "facture transport meubles"],
    ["Licence de transport obligatoire", "Devis obligatoire et gratuit", "Lettre de voiture"],
    [
      { question: "Le devis est-il obligatoire pour un déménagement ?", reponse: "Oui, le devis est obligatoire et gratuit pour toute prestation de déménagement (article L121-20-3 du Code de la consommation). Il doit détailler le volume à transporter (en m³), la distance, le nombre de déménageurs, l'assurance et le prix total TTC." },
      { question: "Quelle assurance dommages le déménageur doit-il proposer ?", reponse: "Le déménageur est responsable des objets transportés (articles 1784 et suivants du Code civil). Il doit proposer une déclaration de valeur et une assurance complémentaire. La responsabilité de base est limitée à un forfait par m³ selon les conditions générales." },
      { question: "Quel taux de TVA pour un déménagement ?", reponse: "Les prestations de déménagement sont soumises à la TVA au taux normal de 20 %. Il n'existe pas de taux réduit pour le déménagement de particuliers, contrairement au transport de voyageurs. La facture doit clairement détailler le montant HT et la TVA." },
      { question: "Comment facturer un déménagement au volume ou au forfait ?", reponse: "La facturation au volume (m³) est la plus courante : estimez le cubage lors de la visite technique, appliquez un tarif au m³ selon la distance. Le forfait tout compris (emballage, transport, déballage) est aussi fréquent. Détaillez chaque poste sur le devis et la facture." },
      { question: "La facturation Factur-X 2026 concerne-t-elle les déménageurs ?", reponse: "Oui. Les déménageurs doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, les TPE et PME devront émettre au format électronique leurs factures aux entreprises (transferts de bureaux, mutations) ; le e-reporting s'appliquera aux déménagements de particuliers." },
    ],
    ["auto-entrepreneur", "chauffagiste", "serrurier", "peintre"],
  ),
  metier("taxi", "Taxi", "service",
    ["facture taxi", "note taxi", "facture course taxi"],
    ["Licence taxi (ADS) obligatoire", "Taximètre obligatoire", "Note obligatoire > 25 €"],
    [
      { question: "Quelle différence entre une note et une facture pour un taxi ?", reponse: "La note de course est obligatoire pour tout montant supérieur à 25 € TTC (arrêté du 3 octobre 1983). Elle doit mentionner la date, le trajet, le montant du compteur et les suppléments. Une facture complète est requise pour les clients professionnels." },
      { question: "Le taximètre est-il obligatoire pour facturer une course ?", reponse: "Oui, le taximètre (compteur horokilométrique) est obligatoire et doit être vérifié annuellement par un organisme agréé (décret n° 2006-1131). Le montant affiché au compteur fait foi et doit correspondre au montant porté sur la note ou la facture." },
      { question: "Quel taux de TVA pour une course de taxi ?", reponse: "Les courses de taxi sont soumises à la TVA au taux réduit de 10 % en tant que transport de voyageurs (article 279-b bis du CGI). En franchise de TVA (article 293 B, seuil 36 800 €), la mention d'exonération doit figurer sur la note." },
      { question: "Comment facturer des courses de taxi pour une entreprise ?", reponse: "Pour les contrats entreprise (courses régulières, salariés), émettez une facture récapitulative mensuelle détaillant chaque course (date, trajet, montant). Cette facture permet au client de récupérer la TVA et de justifier les frais de transport." },
      { question: "La facturation Factur-X 2026 concerne-t-elle les taxis ?", reponse: "Oui. Les taxis doivent pouvoir recevoir des factures électroniques depuis le 1er septembre 2026. À partir du 1er septembre 2027, leurs factures aux entreprises devront être émises au format électronique, et les données des courses aux particuliers transmises à l'administration fiscale (e-reporting)." },
    ],
    ["vtc", "auto-entrepreneur", "demenageur", "consultant"],
  ),
]

export function getMetierBySlug(slug: string): Metier | undefined {
  return METIERS.find(m => m.slug === slug)
}
