export interface Metier {
  slug: string
  nom: string
  titre: string
  description: string
  motsCles: string[]
  features: { titre: string; texte: string }[]
  obligations: string[]
  faq: { question: string; reponse: string }[]
  metiersProches: string[]
}

const BTP_FEATURES = [
  { titre: "Autoliquidation TVA", texte: "Gestion automatique de l'autoliquidation pour la sous-traitance BTP, conforme à l'article 283-2 nonies du CGI." },
  { titre: "Devis détaillés", texte: "Créez des devis professionnels avec lignes de prestations, matériaux, main-d'œuvre et taux de TVA différenciés." },
  { titre: "Suivi de chantier", texte: "Liez vos factures à des devis acceptés et suivez l'avancement financier de chaque chantier." },
]

const SERVICE_FEATURES = [
  { titre: "Factures récurrentes", texte: "Automatisez la facturation de vos prestations mensuelles ou trimestrielles en quelques clics." },
  { titre: "Gestion des acomptes", texte: "Facturez des acomptes et générez automatiquement la facture de solde avec déduction." },
  { titre: "Suivi des paiements", texte: "Visualisez en temps réel les factures payées, en attente et en retard pour gérer votre trésorerie." },
]

const SANTE_FEATURES = [
  { titre: "Notes d'honoraires", texte: "Générez des notes d'honoraires conformes aux obligations de votre profession de santé." },
  { titre: "Franchise de TVA", texte: "Configuration automatique de la franchise en base de TVA (article 293 B du CGI) pour les professions médicales." },
  { titre: "Numérotation séquentielle", texte: "Numérotation chronologique obligatoire avec préfixe personnalisable par année." },
]

const COMMON_FEATURES = [
  { titre: "Factur-X conforme", texte: "Vos factures sont générées au format Factur-X EN 16931, obligatoire pour la facturation électronique 2026." },
  { titre: "Envoi par email", texte: "Envoyez vos factures et devis directement par email depuis l'application, avec suivi de lecture." },
  { titre: "Export comptable FEC", texte: "Exportez votre Fichier des Écritures Comptables (FEC) en un clic pour votre expert-comptable." },
]

const DESCRIPTIONS: Record<string, string> = {
  plombier: "Logiciel de facturation pour plombier : devis détaillés, assurance décennale, autoliquidation TVA sous-traitance. Conforme Factur-X 2026.",
  electricien: "Facturez vos travaux d'électricité avec mentions NF C 15-100, attestation Consuel et assurance décennale. Conforme Factur-X 2026.",
  macon: "Logiciel de facturation maçonnerie : devis gros œuvre, TVA 10 % rénovation / 20 % neuf, export FEC comptable. Conforme Factur-X 2026.",
  peintre: "Créez vos devis peinture au m² avec détail des couches, sous-couche et fournitures. TVA 10 % rénovation. Conforme Factur-X 2026.",
  carreleur: "Devis et factures de pose carrelage : surfaces, matériaux, ragréage. TVA adaptée selon type de travaux. Conforme Factur-X 2026.",
  menuisier: "Facturez vos travaux de menuiserie sur mesure : fabrication, pose, finitions. Marquage CE et décennale. Conforme Factur-X 2026.",
  couvreur: "Logiciel de facturation couverture et toiture : devis tuiles, ardoises, zinc, étanchéité. Décennale intégrée. Conforme Factur-X 2026.",
  plaquiste: "Facturez vos chantiers placo au m² : cloisons, plafonds, isolation, bandes et enduit. Export comptable FEC. Conforme Factur-X 2026.",
  chauffagiste: "Facturez installations et dépannages chauffage : mention RGE, attestation gaz, aides MaPrimeRénov'. Conforme Factur-X 2026.",
  serrurier: "Factures et devis serrurerie : interventions urgence, pose de serrures, tarifs transparents. Conforme Factur-X 2026.",
  "auto-entrepreneur": "Facturez en micro-entreprise avec mention TVA art. 293 B du CGI, numérotation conforme et seuils franchise. Factur-X 2026.",
  consultant: "Logiciel de facturation pour consultant : taux journalier, forfait mission, frais de déplacement, CGV intégrées. Factur-X 2026.",
  "developpeur-freelance": "Facturez vos prestations de développement web et logiciel : livrables, cession de droits, maintenance. Factur-X 2026.",
  graphiste: "Devis et factures création graphique : conception, déclinaisons, cession de droits d'exploitation. Conforme Factur-X 2026.",
  photographe: "Facturez vos reportages photo : prise de vue, retouche, cession de droits d'auteur (CPI L131-3). Conforme Factur-X 2026.",
  formateur: "Factures et conventions de formation : NDA, exonération TVA art. 261-4-4° du CGI, Qualiopi. Conforme Factur-X 2026.",
  coach: "Facturez vos séances de coaching professionnel : forfait, séance unique, présentiel ou visio. Conforme Factur-X 2026.",
  "community-manager": "Facturez vos prestations de community management : forfait mensuel, création de contenu, reporting. Factur-X 2026.",
  traducteur: "Facturez vos traductions au mot ou au feuillet : langues, spécialité, cession de droits. Conforme Factur-X 2026.",
  coiffeur: "Logiciel de facturation salon de coiffure : notes clients, ticket de caisse, affichage prix obligatoire. Conforme Factur-X 2026.",
  estheticienne: "Facturez vos soins esthétiques : prestations détaillées, forfaits, cartes prépayées. Conforme Factur-X 2026.",
  paysagiste: "Devis et factures entretien jardin et aménagement paysager : crédit d'impôt SAP, RC pro. Conforme Factur-X 2026.",
  "architecte-interieur": "Facturez vos honoraires d'architecture intérieure : pourcentage travaux, forfait ou régie. Conforme Factur-X 2026.",
  traiteur: "Devis traiteur détaillés : menu, convives, personnel, matériel, livraison. Normes HACCP. Conforme Factur-X 2026.",
  fleuriste: "Facturez vos compositions florales avec TVA 10 % fleurs coupées et 20 % accessoires. Conforme Factur-X 2026.",
  osteopathe: "Notes d'honoraires ostéopathie : exonération TVA art. 261-4-1° du CGI, numéro ADELI/RPPS. Conforme Factur-X 2026.",
  kinesitherapeute: "Facturez actes conventionnés et hors nomenclature : feuille de soins, RPPS, tiers payant. Conforme Factur-X 2026.",
  "infirmier-liberal": "Facturation soins infirmiers à domicile : Sesam-Vitale, majorations nuit/dimanche, déplacements. Conforme Factur-X 2026.",
  dieteticien: "Notes d'honoraires diététicien : consultations exonérées TVA, numéro ADELI, remboursement mutuelle. Factur-X 2026.",
}

function metier(
  slug: string,
  nom: string,
  categorie: "btp" | "service" | "sante" | "artisanat",
  motsCles: string[],
  obligations: string[],
  faq: { question: string; reponse: string }[],
  metiersProches: string[] = [],
): Metier {
  const catFeatures = categorie === "btp" ? BTP_FEATURES : categorie === "sante" ? SANTE_FEATURES : SERVICE_FEATURES
  return {
    slug,
    nom,
    titre: `Logiciel de facturation pour ${nom}`,
    description: DESCRIPTIONS[slug] ?? `Créez et envoyez vos factures et devis ${nom.toLowerCase()} en quelques clics. Conforme Factur-X 2026, adapté aux ${nom.toLowerCase()}s.`,
    motsCles: [`facturation ${nom.toLowerCase()}`, `facture ${nom.toLowerCase()}`, `devis ${nom.toLowerCase()}`, `logiciel facturation ${nom.toLowerCase()}`, ...motsCles],
    features: [...catFeatures, ...COMMON_FEATURES],
    obligations,
    faq,
    metiersProches,
  }
}

export const METIERS: Metier[] = [
  // ── BTP ──
  metier("plombier", "Plombier", "btp",
    ["facture plomberie", "devis plomberie"],
    ["Devis obligatoire avant travaux (> 150 €)", "Mention de l'assurance décennale sur les devis et factures", "Garantie de parfait achèvement d'un an"],
    [
      { question: "Quelles mentions obligatoires sur une facture de plomberie ?", reponse: "Outre les mentions légales classiques (SIRET, date, numéro séquentiel), une facture de plomberie doit mentionner l'assurance décennale (nom, numéro de contrat, couverture géographique) et le détail des prestations (main-d'œuvre, fournitures, déplacement)." },
      { question: "Un plombier doit-il faire un devis ?", reponse: "Oui, un devis est obligatoire pour tout travail dont le montant dépasse 150 € TTC, ou sur demande du client. Le devis doit détailler les prestations, les matériaux, les délais et le prix total." },
      { question: "Comment facturer un dépannage d'urgence en plomberie ?", reponse: "Le dépannage d'urgence peut être facturé sans devis préalable si le montant est inférieur à 150 €. Mentionnez clairement le tarif horaire, les majorations éventuelles (nuit, week-end) et les fournitures utilisées." },
      { question: "Quel taux de TVA appliquer en plomberie ?", reponse: "Le taux de TVA dépend du type de travaux : 20 % pour les constructions neuves, 10 % pour les travaux de rénovation dans un logement de plus de 2 ans (article 279-0 bis du CGI), et 5,5 % pour les travaux d'amélioration de la performance énergétique." },
      { question: "La facturation électronique Factur-X est-elle obligatoire pour un plombier en 2026 ?", reponse: "Oui, à partir de 2026 la réforme de la facturation électronique impose aux artisans du BTP d'émettre des factures au format structuré (Factur-X EN 16931) pour les transactions B2B. Qonforme génère automatiquement vos factures dans ce format." },
    ],
    ["electricien", "chauffagiste", "macon", "carreleur"],
  ),
  metier("electricien", "Électricien", "btp",
    ["facture electricite", "devis electricite", "norme NF C 15-100"],
    ["Attestation de conformité Consuel après travaux", "Respect de la norme NF C 15-100", "Assurance décennale obligatoire"],
    [
      { question: "Quelles normes mentionner sur une facture d'électricité ?", reponse: "La facture doit faire référence à la norme NF C 15-100 si les travaux concernent une installation neuve ou une rénovation complète. Mentionnez aussi l'attestation Consuel si applicable." },
      { question: "Un électricien doit-il mentionner son assurance décennale ?", reponse: "Oui, l'assurance décennale est obligatoire pour tous les travaux de construction et rénovation. Elle doit figurer sur les devis et factures avec le nom de l'assureur, le numéro de contrat et la zone géographique couverte." },
      { question: "Quel taux de TVA pour des travaux d'électricité ?", reponse: "Le taux est de 20 % pour les constructions neuves, 10 % pour la rénovation de logements de plus de 2 ans (article 279-0 bis du CGI), et 5,5 % pour les travaux d'amélioration énergétique (isolation, chauffage performant)." },
      { question: "Comment facturer au forfait ou au mètre linéaire en électricité ?", reponse: "Les deux modes sont courants : le forfait convient aux installations complètes (tableau, circuit), tandis que le mètre linéaire est utilisé pour le câblage et les chemins de câbles. Détaillez toujours la méthode de calcul sur le devis." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un électricien ?", reponse: "Dès 2026, tout électricien facturant en B2B devra émettre des factures électroniques au format structuré Factur-X. Cette obligation s'applique progressivement selon la taille de l'entreprise, en commençant par les grandes entreprises puis les TPE/PME." },
    ],
    ["plombier", "chauffagiste", "plaquiste", "couvreur"],
  ),
  metier("macon", "Maçon", "btp",
    ["facture maconnerie", "devis maconnerie", "gros oeuvre"],
    ["Assurance décennale obligatoire", "Garantie de parfait achèvement", "Devis détaillé obligatoire pour travaux > 150 €"],
    [
      { question: "Comment facturer des travaux de maçonnerie ?", reponse: "Détaillez chaque poste : terrassement, fondations, élévation des murs, fournitures (parpaings, ciment, ferraillage). Séparez main-d'œuvre et matériaux avec les taux de TVA applicables (10% rénovation, 20% neuf)." },
      { question: "Quel taux de TVA pour des travaux de maçonnerie ?", reponse: "Le taux dépend du type de travaux : 20% pour la construction neuve, 10% pour la rénovation/amélioration de logements de plus de 2 ans, 5,5% pour les travaux d'amélioration énergétique." },
      { question: "L'assurance décennale est-elle obligatoire pour un maçon ?", reponse: "Oui, la garantie décennale est obligatoire pour tout constructeur au sens de l'article 1792 du Code civil. Elle couvre les dommages compromettant la solidité de l'ouvrage pendant 10 ans. Ses références doivent figurer sur tous les devis et factures." },
      { question: "Comment facturer la sous-traitance en maçonnerie (autoliquidation) ?", reponse: "En cas de sous-traitance BTP, c'est le donneur d'ordre qui reverse la TVA (article 283-2 nonies du CGI). Le sous-traitant maçon émet une facture HT avec la mention « Autoliquidation de la TVA » sans collecter de TVA." },
      { question: "La facturation électronique Factur-X concerne-t-elle les maçons ?", reponse: "Oui, la réforme 2026 de la facturation électronique s'applique à tous les professionnels du BTP, y compris les maçons. Les factures B2B devront être émises au format Factur-X EN 16931 via une plateforme de dématérialisation." },
    ],
    ["plombier", "carreleur", "couvreur", "peintre"],
  ),
  metier("peintre", "Peintre en bâtiment", "btp",
    ["facture peinture", "devis peinture batiment"],
    ["Devis détaillé avec surfaces et nombre de couches", "Assurance responsabilité civile professionnelle", "Respect des normes environnementales (COV)"],
    [
      { question: "Comment établir un devis de peinture ?", reponse: "Un devis de peinture doit détailler : les surfaces à peindre (en m²), le nombre de couches, le type de peinture, la préparation des supports (ponçage, enduit, sous-couche), et séparer main-d'œuvre et fournitures." },
      { question: "Quel taux de TVA pour des travaux de peinture ?", reponse: "10% pour la rénovation de logements achevés depuis plus de 2 ans, 20% pour les constructions neuves ou les locaux professionnels." },
      { question: "Un peintre en bâtiment doit-il souscrire une assurance décennale ?", reponse: "Oui, la décennale est obligatoire dès lors que les travaux de peinture affectent l'étanchéité ou la protection de l'ouvrage (peinture extérieure, imperméabilisation). Pour la peinture intérieure décorative, la RC professionnelle suffit généralement." },
      { question: "Comment facturer des travaux de peinture au m² ?", reponse: "Indiquez la surface totale en m², le prix unitaire au m² (qui inclut main-d'œuvre et fournitures ou les sépare), le nombre de couches et le type de finition. Ce mode de facturation est le plus transparent pour le client." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un peintre ?", reponse: "Comme tous les artisans du BTP, les peintres en bâtiment devront émettre des factures électroniques au format Factur-X EN 16931 pour leurs clients professionnels à partir de 2026. Qonforme intègre ce format nativement." },
    ],
    ["plaquiste", "carreleur", "macon", "menuisier"],
  ),
  metier("carreleur", "Carreleur", "btp",
    ["facture carrelage", "devis pose carrelage"],
    ["Assurance décennale obligatoire", "Devis avec détail des surfaces et matériaux"],
    [
      { question: "Comment facturer une pose de carrelage ?", reponse: "Détaillez la surface (m²), le type de carrelage (grès cérame, faïence), la pose (droite, diagonale, décalée), les fournitures (colle, joints, croisillons) et les travaux de préparation (ragréage, chape)." },
      { question: "Quel taux de TVA pour la pose de carrelage ?", reponse: "Le taux réduit de 10 % s'applique pour la pose de carrelage dans un logement de plus de 2 ans (article 279-0 bis du CGI). Le taux normal de 20 % s'applique pour les constructions neuves et les locaux professionnels." },
      { question: "L'assurance décennale est-elle obligatoire pour un carreleur ?", reponse: "Oui, le carreleur réalise des travaux d'ouvrage et doit souscrire une assurance décennale (article 1792 du Code civil). Cette garantie couvre les défauts de pose (infiltrations, décollements) pendant 10 ans après la réception des travaux." },
      { question: "Comment établir un devis de carrelage au m² ?", reponse: "Indiquez la surface totale en m², le prix au m² pour la fourniture et la pose séparément, les découpes spéciales (angles, plinthes), et les travaux préparatoires. Précisez le type de pose car une pose diagonale coûte plus cher qu'une pose droite." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un carreleur ?", reponse: "À partir de 2026, les carreleurs devront émettre des factures électroniques au format structuré Factur-X pour toute transaction B2B. Cette obligation concerne aussi les factures de sous-traitance avec autoliquidation de TVA." },
    ],
    ["macon", "peintre", "plombier", "menuisier"],
  ),
  metier("menuisier", "Menuisier", "btp",
    ["facture menuiserie", "devis menuiserie"],
    ["Assurance décennale pour les ouvrages structurels", "Marquage CE pour les menuiseries extérieures"],
    [
      { question: "Comment facturer des travaux de menuiserie ?", reponse: "Distinguez la fabrication sur mesure (matériaux, heures d'atelier) de la pose (déplacement, installation, finitions). Précisez le type de bois et les traitements appliqués." },
      { question: "Quel taux de TVA pour des travaux de menuiserie ?", reponse: "Le taux de 10 % s'applique à la pose de menuiseries dans un logement de plus de 2 ans. Le taux de 5,5 % s'applique aux menuiseries améliorant la performance énergétique (fenêtres isolantes, portes d'entrée). Le taux de 20 % s'applique au neuf." },
      { question: "L'assurance décennale est-elle obligatoire pour un menuisier ?", reponse: "Oui, pour les ouvrages structurels (charpente, escalier, menuiseries extérieures). La décennale couvre les dommages compromettant la solidité ou rendant l'ouvrage impropre à sa destination pendant 10 ans (article 1792 du Code civil)." },
      { question: "Comment facturer la fabrication sur mesure et la pose séparément ?", reponse: "Créez deux sections distinctes sur votre facture : la fabrication (matériaux bois, quincaillerie, heures d'atelier) et la pose (déplacement, installation, ajustements). Ce détail facilite l'application des bons taux de TVA." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un menuisier ?", reponse: "Dès 2026, la facturation électronique au format Factur-X devient obligatoire pour les menuisiers facturant des professionnels. Les factures devront transiter par une plateforme de dématérialisation partenaire (PDP) ou le portail public." },
    ],
    ["couvreur", "peintre", "plaquiste", "carreleur"],
  ),
  metier("couvreur", "Couvreur", "btp",
    ["facture toiture", "devis couverture"],
    ["Assurance décennale obligatoire", "Respect des DTU couverture"],
    [
      { question: "Quelles mentions sur un devis de couverture ?", reponse: "Le devis doit préciser le type de couverture (tuiles, ardoises, zinc), la surface en m², les travaux d'étanchéité, la pose de gouttières, et l'évacuation des déchets. L'assurance décennale est impérative." },
      { question: "Quel taux de TVA pour des travaux de toiture ?", reponse: "Le taux de 10 % s'applique à la réfection de toiture d'un logement de plus de 2 ans. Le taux de 5,5 % concerne les travaux d'isolation de toiture améliorant la performance énergétique. Le taux normal de 20 % s'applique aux constructions neuves." },
      { question: "L'assurance décennale est-elle obligatoire pour un couvreur ?", reponse: "Oui, absolument. La toiture étant un élément de clos et de couvert, elle relève de la garantie décennale (article 1792 du Code civil). Tout couvreur doit mentionner son assurance décennale sur ses devis et factures." },
      { question: "Comment facturer des travaux de couverture au m² ?", reponse: "Indiquez la surface totale en m², le prix au m² pour la dépose de l'ancienne couverture, la fourniture des matériaux neufs et la pose. Séparez les postes accessoires : zinguerie, gouttières, ventilation, échafaudage." },
      { question: "Un couvreur est-il concerné par la facturation Factur-X 2026 ?", reponse: "Oui, tous les artisans du BTP, y compris les couvreurs, sont soumis à l'obligation de facturation électronique Factur-X pour les échanges B2B à partir de 2026. Cela concerne aussi les factures de sous-traitance." },
    ],
    ["macon", "menuisier", "plaquiste", "chauffagiste"],
  ),
  metier("plaquiste", "Plaquiste", "btp",
    ["facture placo", "devis plaquiste", "cloison seche"],
    ["Assurance décennale", "Respect des DTU plâtrerie"],
    [
      { question: "Comment facturer des travaux de plâtrerie ?", reponse: "Facturez au m² pour les cloisons et plafonds. Détaillez : type de plaques (BA13, hydrofuge, phonique), ossature, isolation, bandes et finitions (enduit, ponçage)." },
      { question: "Quel taux de TVA pour des travaux de plaquiste ?", reponse: "Le taux réduit de 10 % s'applique aux travaux de cloisons et faux plafonds dans un logement de plus de 2 ans. Le taux de 5,5 % concerne les travaux d'isolation thermique (doublage avec isolant). Le neuf est à 20 %." },
      { question: "Un plaquiste doit-il souscrire une assurance décennale ?", reponse: "Oui, les travaux de plâtrerie sèche (cloisons, doublages, faux plafonds) constituent des ouvrages couverts par la garantie décennale dès lors qu'ils participent à la solidité ou à l'habitabilité du bâtiment (article 1792 du Code civil)." },
      { question: "Comment facturer la sous-traitance en plâtrerie avec autoliquidation ?", reponse: "Si vous intervenez comme sous-traitant, facturez HT avec la mention « Autoliquidation — article 283-2 nonies du CGI ». C'est le donneur d'ordre qui déclare et reverse la TVA. Aucune TVA ne doit apparaître sur votre facture." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un plaquiste ?", reponse: "À partir de 2026, les plaquistes devront émettre des factures au format électronique structuré Factur-X EN 16931 pour leurs clients professionnels. Le e-reporting sera aussi requis pour les ventes aux particuliers." },
    ],
    ["peintre", "electricien", "menuisier", "macon"],
  ),
  metier("chauffagiste", "Chauffagiste", "btp",
    ["facture chauffage", "devis installation chauffage"],
    ["Qualification RGE pour les aides énergétiques", "Attestation de conformité gaz"],
    [
      { question: "Un chauffagiste doit-il être RGE ?", reponse: "La qualification RGE (Reconnu Garant de l'Environnement) n'est pas obligatoire mais elle permet à vos clients de bénéficier des aides (MaPrimeRénov', CEE). Mentionnez-la sur vos devis et factures." },
      { question: "Quel taux de TVA pour l'installation d'un chauffage ?", reponse: "Le taux de 5,5 % s'applique aux équipements de chauffage performants (pompe à chaleur, chaudière à condensation) dans un logement de plus de 2 ans. Le taux de 10 % s'applique aux autres travaux de rénovation. Le neuf est à 20 %." },
      { question: "L'assurance décennale est-elle obligatoire pour un chauffagiste ?", reponse: "Oui, les installations de chauffage sont des éléments d'équipement indissociables du bâtiment couverts par la garantie décennale (article 1792 du Code civil). Le chauffagiste doit mentionner son assureur et son numéro de contrat sur chaque devis." },
      { question: "Comment facturer l'entretien annuel d'une chaudière ?", reponse: "L'entretien annuel obligatoire (décret n° 2009-649) se facture généralement au forfait. Détaillez les opérations effectuées (nettoyage, vérifications, mesure de combustion) et remettez l'attestation d'entretien au client." },
      { question: "Un chauffagiste est-il concerné par Factur-X 2026 ?", reponse: "Oui, comme tous les professionnels du BTP, les chauffagistes devront émettre des factures électroniques au format Factur-X pour les transactions B2B. Les factures aux particuliers feront l'objet du e-reporting." },
    ],
    ["plombier", "electricien", "couvreur", "macon"],
  ),
  metier("serrurier", "Serrurier", "btp",
    ["facture serrurerie", "devis serrurier"],
    ["Affichage des tarifs obligatoire", "Devis obligatoire avant intervention (sauf urgence < 150 €)"],
    [
      { question: "Comment facturer une intervention de serrurerie ?", reponse: "Détaillez le déplacement, la main-d'œuvre (avec tarif horaire), les fournitures (cylindre, serrure, poignée) et les majorations éventuelles (nuit, dimanche). Pour les urgences < 150 €, le devis n'est pas obligatoire." },
      { question: "Quel taux de TVA pour des travaux de serrurerie ?", reponse: "Le taux de 10 % s'applique aux travaux de remplacement de serrures et blindage de portes dans un logement de plus de 2 ans. Le taux de 20 % s'applique aux constructions neuves et aux locaux professionnels." },
      { question: "Un serrurier doit-il afficher ses tarifs ?", reponse: "Oui, l'arrêté du 24 janvier 2017 impose l'affichage des tarifs pour les prestations de dépannage, réparation et entretien. Le serrurier doit afficher ses tarifs TTC (déplacement, main-d'œuvre horaire, majorations) dans son véhicule et sur son site." },
      { question: "Quelle assurance est obligatoire pour un serrurier ?", reponse: "La RC professionnelle est obligatoire pour couvrir les dommages causés lors des interventions. L'assurance décennale est requise uniquement pour les travaux affectant la structure du bâtiment (blindage de porte d'entrée, par exemple)." },
      { question: "La facturation Factur-X 2026 concerne-t-elle les serruriers ?", reponse: "Oui, les serruriers devront émettre des factures électroniques Factur-X pour les clients professionnels à partir de 2026. Pour les particuliers, un e-reporting des données de facturation sera également requis." },
    ],
    ["menuisier", "electricien", "plombier", "peintre"],
  ),

  // ── Services / Freelance ──
  metier("auto-entrepreneur", "Auto-entrepreneur", "service",
    ["facture auto entrepreneur", "modele facture micro entreprise"],
    ["Mention « TVA non applicable, art. 293 B du CGI » si franchise", "Numéro SIRET obligatoire", "Numérotation chronologique des factures"],
    [
      { question: "Comment faire une facture en auto-entrepreneur ?", reponse: "La facture doit comporter : vos coordonnées et SIRET, celles du client, la date, un numéro séquentiel, le détail des prestations, le montant HT, et la mention « TVA non applicable, art. 293 B du CGI » si vous êtes en franchise de TVA." },
      { question: "Un auto-entrepreneur doit-il facturer la TVA ?", reponse: "Non, tant que vous restez sous les seuils de franchise (36 800 € pour les services, 91 900 € pour la vente). Au-delà, vous devez facturer la TVA et la reverser." },
      { question: "Comment gérer les frais de déplacement en auto-entrepreneur ?", reponse: "Vous pouvez refacturer les frais de déplacement au client en les intégrant comme une ligne distincte sur la facture. En micro-entreprise, les frais ne sont pas déductibles : ils s'ajoutent à votre chiffre d'affaires déclaré." },
      { question: "Quelles sont les pénalités de retard obligatoires sur une facture auto-entrepreneur ?", reponse: "Toute facture doit mentionner le taux de pénalités de retard (minimum : taux BCE + 10 points) et l'indemnité forfaitaire de 40 € pour frais de recouvrement, conformément aux articles L441-10 et D441-5 du Code de commerce." },
      { question: "Un auto-entrepreneur est-il concerné par Factur-X 2026 ?", reponse: "Oui, la facturation électronique s'appliquera progressivement aux micro-entreprises. Dès 2026, vous devrez au minimum recevoir des factures électroniques, puis émettre au format Factur-X pour vos clients professionnels." },
    ],
    ["consultant", "developpeur-freelance", "graphiste", "photographe"],
  ),
  metier("consultant", "Consultant", "service",
    ["facture consultant", "facture prestation conseil"],
    ["Conditions générales de vente recommandées", "Mentions obligatoires classiques"],
    [
      { question: "Comment facturer une prestation de conseil ?", reponse: "Précisez la nature de la mission, la période, le taux journalier ou le forfait, les frais éventuels (déplacement, hébergement) et les conditions de paiement." },
      { question: "Comment refacturer des frais de déplacement en tant que consultant ?", reponse: "Les frais de déplacement peuvent être refacturés au réel (sur justificatifs) ou au forfait. Créez une ligne séparée « Frais de déplacement » sur la facture, soumise au même taux de TVA que la prestation principale." },
      { question: "Quels sont les délais de paiement légaux pour une facture de consulting ?", reponse: "Le délai maximum est de 60 jours à compter de la date de facturation, ou 45 jours fin de mois (article L441-10 du Code de commerce). Les pénalités de retard et l'indemnité forfaitaire de 40 € doivent figurer sur la facture." },
      { question: "Un consultant doit-il facturer la TVA ?", reponse: "Oui, sauf en franchise de TVA (seuil de 36 800 € pour les prestations de services). Au-delà, le consultant collecte la TVA à 20 % et la reverse à l'État. Pour les clients étrangers (UE), l'autoliquidation peut s'appliquer." },
      { question: "Quelles sont les obligations Factur-X 2026 pour un consultant ?", reponse: "Dès 2026, les consultants devront émettre des factures électroniques au format Factur-X pour tous leurs clients professionnels français. Cette obligation vise à automatiser les contrôles fiscaux et réduire la fraude à la TVA." },
    ],
    ["auto-entrepreneur", "formateur", "coach", "developpeur-freelance"],
  ),
  metier("developpeur-freelance", "Développeur freelance", "service",
    ["facture developpeur", "facture freelance informatique"],
    ["Cession de droits d'auteur à préciser", "Conditions de maintenance et support"],
    [
      { question: "Comment facturer une prestation de développement ?", reponse: "Détaillez les livrables (site web, application, API), le volume (jours/homme ou forfait), la cession de droits éventuelle, et les conditions de maintenance. Précisez si le code source est livré." },
      { question: "Comment facturer la cession de droits d'auteur sur un logiciel ?", reponse: "La cession de droits sur le code source doit faire l'objet d'une ligne distincte sur la facture (article L131-3 du CPI). Précisez l'étendue (droits patrimoniaux cédés), la durée, le territoire et les supports autorisés." },
      { question: "Un développeur freelance doit-il facturer la TVA ?", reponse: "Oui, sauf en franchise de TVA (seuil de 36 800 € pour les services). Pour les clients dans l'UE, la TVA est autoliquidée par le client (mention obligatoire du numéro de TVA intracommunautaire sur la facture)." },
      { question: "Comment gérer les acomptes sur un projet de développement ?", reponse: "Émettez une facture d'acompte (30 à 50 % du montant total est courant) avant le démarrage, puis une facture de solde à la livraison. Chaque facture d'acompte doit comporter un numéro séquentiel et les mentions légales complètes." },
      { question: "Quelles obligations Factur-X 2026 pour un développeur freelance ?", reponse: "Les développeurs freelances devront émettre des factures électroniques Factur-X pour leurs clients professionnels dès 2026. Les plateformes de facturation comme Qonforme génèrent automatiquement le format conforme EN 16931." },
    ],
    ["graphiste", "consultant", "community-manager", "auto-entrepreneur"],
  ),
  metier("graphiste", "Graphiste", "service",
    ["facture graphiste", "devis creation graphique"],
    ["Cession de droits d'exploitation à détailler", "Nombre de révisions à préciser"],
    [
      { question: "Comment facturer une création graphique ?", reponse: "Séparez la création (recherche, conception, déclinaisons) de la cession de droits (exclusifs ou non, durée, supports). Précisez le nombre de propositions et de révisions incluses." },
      { question: "Comment facturer la cession de droits d'exploitation en graphisme ?", reponse: "La cession de droits doit être détaillée sur la facture conformément à l'article L131-3 du Code de la propriété intellectuelle : nature des droits cédés, étendue (supports, territoire), durée et rémunération distincte de la prestation créative." },
      { question: "Un graphiste freelance doit-il facturer la TVA ?", reponse: "Oui, sauf en franchise de TVA (seuil de 36 800 €). La TVA applicable est de 20 % sur les prestations de création graphique. Pour les clients dans l'UE assujettis, la TVA est autoliquidée par le client." },
      { question: "Comment gérer les frais d'achat (typos, images) sur une facture de graphiste ?", reponse: "Les achats de typographies, images stock ou impressions réalisés pour le compte du client peuvent être refacturés sur une ligne séparée avec le même taux de TVA. Conservez les justificatifs pour votre comptabilité." },
      { question: "Quelles obligations Factur-X 2026 pour un graphiste ?", reponse: "Dès 2026, les graphistes devront émettre des factures électroniques au format Factur-X pour leurs clients professionnels. Cette obligation s'accompagne du e-reporting pour les transactions avec les particuliers et clients étrangers." },
    ],
    ["photographe", "developpeur-freelance", "community-manager", "auto-entrepreneur"],
  ),
  metier("photographe", "Photographe", "service",
    ["facture photographe", "devis reportage photo"],
    ["Droits d'auteur et cession de droits à préciser", "TVA à 10% sur certaines prestations artistiques"],
    [
      { question: "Comment facturer un reportage photo ?", reponse: "Distinguez la prise de vue (tarif journée/demi-journée), le post-traitement (retouches, sélection), la cession de droits (usage, durée, supports) et les frais (déplacement, matériel spécifique)." },
      { question: "Quel taux de TVA pour un photographe ?", reponse: "Le taux standard de 20 % s'applique à la majorité des prestations photo. Cependant, les cessions de droits d'auteur sur des œuvres originales peuvent bénéficier du taux réduit de 10 % (article 278-0 bis du CGI) si le photographe est auteur." },
      { question: "Comment facturer la cession de droits sur des photos ?", reponse: "La cession de droits doit être une ligne séparée précisant : les droits cédés (reproduction, diffusion), les supports (web, print, affichage), le territoire, la durée et l'exclusivité éventuelle, conformément à l'article L131-3 du CPI." },
      { question: "Un photographe auto-entrepreneur doit-il facturer la TVA ?", reponse: "Non, tant qu'il reste sous le seuil de franchise de TVA (36 800 € pour les prestations de services). La mention « TVA non applicable, art. 293 B du CGI » doit figurer sur chaque facture. Au-delà du seuil, la TVA est obligatoire." },
      { question: "Quelles obligations Factur-X 2026 pour un photographe ?", reponse: "Les photographes devront émettre des factures au format électronique Factur-X pour leurs clients professionnels dès 2026. Cela concerne les reportages corporate, événementiels et toute prestation facturée à une entreprise." },
    ],
    ["graphiste", "community-manager", "auto-entrepreneur", "traducteur"],
  ),
  metier("formateur", "Formateur", "service",
    ["facture formation", "convention de formation"],
    ["Convention de formation obligatoire", "Numéro de déclaration d'activité (NDA)", "Exonération de TVA possible (art. 261-4-4° du CGI)"],
    [
      { question: "Un formateur doit-il facturer la TVA ?", reponse: "Les organismes de formation peuvent être exonérés de TVA (article 261-4-4° du CGI) en obtenant une attestation auprès de la DREETS. Cette exonération doit être mentionnée sur les factures." },
      { question: "Quelles mentions obligatoires sur une facture de formation ?", reponse: "En plus des mentions légales classiques, une facture de formation doit mentionner le numéro de déclaration d'activité (NDA), l'intitulé de la formation, les dates, la durée en heures, le nombre de stagiaires et le lieu." },
      { question: "Comment facturer une formation financée par un OPCO ?", reponse: "Facturez l'OPCO directement (subrogation de paiement) ou le client qui se fait rembourser. La convention de formation tripartite doit être signée avant le début. Les OPCO exigent souvent un numéro de certification Qualiopi." },
      { question: "Comment gérer les frais annexes sur une facture de formation ?", reponse: "Les frais de déplacement, d'hébergement et de restauration du formateur peuvent être refacturés au réel ou au forfait. Créez des lignes distinctes sur la facture pour séparer les honoraires pédagogiques des frais annexes." },
      { question: "Quelles obligations Factur-X 2026 pour un formateur indépendant ?", reponse: "Les formateurs devront émettre des factures au format Factur-X pour leurs clients professionnels et OPCO dès 2026. Cette obligation s'applique même aux formateurs exonérés de TVA : le format structuré est indépendant du régime fiscal." },
    ],
    ["consultant", "coach", "auto-entrepreneur", "traducteur"],
  ),
  metier("coach", "Coach professionnel", "service",
    ["facture coaching", "devis accompagnement"],
    ["Mentions obligatoires classiques", "CGV recommandées"],
    [
      { question: "Comment facturer une séance de coaching ?", reponse: "Facturez à la séance ou au forfait (pack de séances). Précisez la durée, le lieu (présentiel/visio), et les conditions d'annulation." },
      { question: "Un coach professionnel doit-il facturer la TVA ?", reponse: "Oui, les prestations de coaching sont soumises à la TVA au taux de 20 %, sauf si le coach bénéficie de la franchise en base de TVA (seuil de 36 800 € de CA annuel, article 293 B du CGI)." },
      { question: "Comment facturer un pack de séances de coaching ?", reponse: "Émettez une facture pour le pack complet avec le détail : nombre de séances, durée unitaire, prix unitaire et prix total du pack. Si le paiement est échelonné, émettez une facture d'acompte puis une facture de solde." },
      { question: "Quels délais de paiement appliquer pour du coaching ?", reponse: "Le délai légal maximum est de 60 jours date de facture ou 45 jours fin de mois (article L441-10 du Code de commerce). En pratique, beaucoup de coachs facturent avant la prestation ou au comptant pour sécuriser leur trésorerie." },
      { question: "Quelles obligations Factur-X 2026 pour un coach ?", reponse: "Les coachs professionnels facturant des entreprises devront émettre des factures électroniques au format Factur-X dès 2026. Cela concerne le coaching individuel dirigeant, le coaching d'équipe et toute prestation B2B." },
    ],
    ["formateur", "consultant", "community-manager", "auto-entrepreneur"],
  ),
  metier("community-manager", "Community manager", "service",
    ["facture community management", "devis gestion reseaux sociaux"],
    ["Mentions obligatoires classiques", "Périmètre de la mission à détailler"],
    [
      { question: "Comment facturer du community management ?", reponse: "Facturez au forfait mensuel en détaillant : nombre de publications par réseau, création de contenu (visuels, vidéos), modération, reporting. Précisez les réseaux concernés." },
      { question: "Comment facturer les frais publicitaires (ads) en community management ?", reponse: "Les budgets publicitaires avancés pour le client doivent être refacturés sur une ligne séparée (débours ou refacturation de frais). Précisez si vous facturez un pourcentage de gestion en sus du budget média dépensé." },
      { question: "Un community manager freelance doit-il facturer la TVA ?", reponse: "Oui, au taux de 20 %, sauf en franchise de TVA (seuil de 36 800 € de CA annuel). Pour les clients dans l'UE, la TVA est autoliquidée. Mentionnez le numéro de TVA intracommunautaire du client sur la facture." },
      { question: "Comment protéger sa propriété intellectuelle en community management ?", reponse: "Les visuels et textes créés restent la propriété du community manager jusqu'à cession explicite. Précisez dans vos CGV et sur la facture si les droits d'exploitation sont cédés au client ou s'il dispose d'une simple licence d'utilisation." },
      { question: "Quelles obligations Factur-X 2026 pour un community manager ?", reponse: "Les community managers facturant des entreprises devront émettre des factures au format Factur-X EN 16931 dès 2026. Cette obligation concerne toutes les prestations B2B, y compris les forfaits mensuels récurrents." },
    ],
    ["graphiste", "developpeur-freelance", "photographe", "consultant"],
  ),
  metier("traducteur", "Traducteur", "service",
    ["facture traduction", "devis traduction"],
    ["Cession de droits si traduction littéraire", "Tarif au mot ou au feuillet"],
    [
      { question: "Comment facturer une traduction ?", reponse: "Facturez au mot (tarif standard en traduction technique) ou au feuillet (1 500 signes espaces comprises). Précisez les langues, le domaine de spécialité et le délai de livraison." },
      { question: "Comment facturer la cession de droits sur une traduction littéraire ?", reponse: "Pour les traductions littéraires, la cession de droits d'auteur doit être détaillée conformément à l'article L131-3 du CPI : étendue des droits, durée, territoire et supports. La rémunération de la cession doit être distincte des honoraires de traduction." },
      { question: "Un traducteur freelance doit-il facturer la TVA ?", reponse: "Oui, au taux de 20 %, sauf en franchise de TVA (seuil de 36 800 €). Pour les clients professionnels dans l'UE, la TVA est autoliquidée par le client. Pensez à vérifier et mentionner le numéro de TVA intracommunautaire." },
      { question: "Comment gérer les pénalités de retard sur une facture de traduction ?", reponse: "La facture doit mentionner le taux de pénalités de retard applicable (minimum : taux directeur BCE + 10 points) et l'indemnité forfaitaire de 40 € pour frais de recouvrement, conformément à l'article L441-10 du Code de commerce." },
      { question: "Quelles obligations Factur-X 2026 pour un traducteur ?", reponse: "Les traducteurs devront émettre des factures électroniques Factur-X pour leurs clients professionnels français dès 2026. Pour les clients étrangers, le e-reporting des données de transaction sera requis auprès de l'administration fiscale." },
    ],
    ["formateur", "consultant", "graphiste", "auto-entrepreneur"],
  ),

  // ── Artisanat / Commerce ──
  metier("coiffeur", "Coiffeur", "artisanat",
    ["facture salon coiffure", "logiciel caisse coiffeur"],
    ["Affichage des prix obligatoire", "Note/facture obligatoire au-delà de 25 €"],
    [
      { question: "Un coiffeur doit-il faire des factures ?", reponse: "Une note (ticket) suffit pour les particuliers si le montant est inférieur à 25 €. Au-delà, une note détaillée est obligatoire. Pour les clients professionnels, une facture complète est toujours requise." },
      { question: "Quel taux de TVA pour un salon de coiffure ?", reponse: "Le taux de TVA est de 20 % pour l'ensemble des prestations de coiffure (coupes, colorations, soins). La vente de produits capillaires est également soumise au taux de 20 %. Il n'existe pas de taux réduit pour la coiffure." },
      { question: "Un coiffeur doit-il afficher ses prix ?", reponse: "Oui, l'affichage des prix TTC est obligatoire (arrêté du 27 mars 1987). Les tarifs doivent être visibles de l'extérieur pour les prestations courantes et à l'intérieur pour l'ensemble des prestations, hommes et femmes séparément." },
      { question: "Comment facturer la vente de produits en salon de coiffure ?", reponse: "La vente de produits (shampoings, soins, accessoires) doit apparaître sur une ligne distincte de la prestation de coiffure. Le taux de TVA est identique (20 %) mais la distinction facilite le suivi comptable et la gestion des stocks." },
      { question: "Quelles obligations Factur-X 2026 pour un coiffeur ?", reponse: "Les coiffeurs facturant des clients professionnels (contrats entreprise, spectacles) devront émettre des factures Factur-X dès 2026. Pour les particuliers, le e-reporting sera requis pour transmettre les données de vente à l'administration fiscale." },
    ],
    ["estheticienne", "auto-entrepreneur", "fleuriste", "traiteur"],
  ),
  metier("estheticienne", "Esthéticienne", "artisanat",
    ["facture institut beaute", "logiciel facturation esthetique"],
    ["Affichage des prix obligatoire", "Note/facture obligatoire"],
    [
      { question: "Comment facturer des soins esthétiques ?", reponse: "Détaillez chaque prestation (soin visage, épilation, manucure) avec son prix unitaire. Pour les forfaits et cartes prépayées, précisez la validité et les conditions d'utilisation." },
      { question: "Quel taux de TVA pour un institut de beauté ?", reponse: "Le taux de TVA est de 20 % pour l'ensemble des prestations esthétiques (soins, épilations, manucures, maquillage). La revente de produits cosmétiques est également soumise au taux normal de 20 %." },
      { question: "À partir de quel montant une esthéticienne doit-elle délivrer une note ?", reponse: "Une note détaillée est obligatoire dès que le montant dépasse 25 € TTC pour un client particulier (arrêté du 3 octobre 1983). En dessous, la remise d'une note reste recommandée mais n'est pas obligatoire." },
      { question: "Comment gérer les cartes prépayées et abonnements en institut ?", reponse: "Émettez une facture lors de la vente de la carte ou de l'abonnement. Le chiffre d'affaires est comptabilisé au fur et à mesure de l'utilisation des séances (produit constaté d'avance). Précisez la durée de validité et les conditions de remboursement." },
      { question: "Quelles obligations Factur-X 2026 pour une esthéticienne ?", reponse: "Les esthéticiennes facturant des entreprises (comités d'entreprise, hôtels, spas) devront émettre des factures Factur-X dès 2026. Le e-reporting concernera les ventes aux particuliers pour la transmission des données à l'administration fiscale." },
    ],
    ["coiffeur", "auto-entrepreneur", "fleuriste", "dieteticien"],
  ),
  metier("paysagiste", "Paysagiste", "btp",
    ["facture entretien jardin", "devis amenagement paysager"],
    ["Devis obligatoire pour travaux > 150 €", "Assurance RC professionnelle"],
    [
      { question: "Comment facturer un entretien de jardin ?", reponse: "Facturez à l'heure ou au forfait. Détaillez : tonte, taille, désherbage, évacuation des déchets verts. Pour les particuliers, le crédit d'impôt SAP (50%) s'applique à l'entretien courant." },
      { question: "Quel taux de TVA pour des travaux de paysagisme ?", reponse: "Le taux de 20 % s'applique aux travaux de création (aménagement, plantation, terrassement). Le taux de 10 % peut s'appliquer à l'entretien de jardins attenants à un logement de plus de 2 ans. Les prestations SAP d'entretien courant sont à 20 %." },
      { question: "Un paysagiste doit-il souscrire une assurance décennale ?", reponse: "L'assurance décennale est obligatoire pour les ouvrages paysagers structurels (murs de soutènement, terrasses, allées carrossables). Pour l'entretien et les plantations, la RC professionnelle suffit généralement." },
      { question: "Comment facturer un contrat d'entretien annuel de jardin ?", reponse: "Proposez un forfait annuel avec un calendrier d'interventions (mensuel ou trimestriel). Détaillez les prestations incluses (tonte, taille, traitement) et émettez une facture par passage ou une facture mensuelle selon l'accord." },
      { question: "Un paysagiste est-il concerné par Factur-X 2026 ?", reponse: "Oui, les paysagistes devront émettre des factures électroniques Factur-X pour les clients professionnels (copropriétés, entreprises, collectivités) dès 2026. Le e-reporting s'appliquera pour les prestations aux particuliers." },
    ],
    ["macon", "menuisier", "carreleur", "fleuriste"],
  ),
  metier("architecte-interieur", "Architecte d'intérieur", "service",
    ["facture architecte interieur", "devis decoration interieure", "honoraires architecte"],
    ["Barème d'honoraires à communiquer", "Assurance RC professionnelle"],
    [
      { question: "Comment facturer des honoraires d'architecte d'intérieur ?", reponse: "Facturez au pourcentage du montant des travaux (8-15%), au forfait, ou en régie (taux horaire/journalier). Détaillez les phases : étude, conception, plans, suivi de chantier." },
      { question: "Un architecte d'intérieur doit-il facturer la TVA ?", reponse: "Oui, les honoraires d'architecte d'intérieur sont soumis à la TVA au taux de 20 %. En franchise de TVA (seuil 36 800 €), mentionnez « TVA non applicable, art. 293 B du CGI ». Les achats de mobilier refacturés suivent leur propre taux." },
      { question: "Comment refacturer les achats de mobilier et matériaux ?", reponse: "Deux options : la refacturation (vous achetez et revendez avec marge, TVA sur le tout) ou le débours (vous achetez au nom du client, aucune TVA sur le remboursement). La méthode choisie doit être claire dans le contrat et sur la facture." },
      { question: "Quelles pénalités de retard mentionner sur une facture d'architecte d'intérieur ?", reponse: "La facture doit indiquer le taux de pénalités de retard (minimum : taux directeur BCE + 10 points) et l'indemnité forfaitaire de 40 € pour frais de recouvrement, conformément aux articles L441-10 et D441-5 du Code de commerce." },
      { question: "Quelles obligations Factur-X 2026 pour un architecte d'intérieur ?", reponse: "Les architectes d'intérieur devront émettre des factures Factur-X pour leurs clients professionnels dès 2026. Les factures de suivi de chantier, honoraires de conception et achats refacturés sont tous concernés par cette obligation." },
    ],
    ["peintre", "menuisier", "carreleur", "graphiste"],
  ),
  metier("traiteur", "Traiteur", "artisanat",
    ["facture traiteur", "devis reception traiteur"],
    ["Respect des normes HACCP", "Devis détaillé avec menu"],
    [
      { question: "Comment établir un devis de traiteur ?", reponse: "Détaillez : nombre de convives, menu (entrée, plat, dessert, boissons), formule (buffet, assis), matériel (vaisselle, nappes), personnel de service, livraison et installation." },
      { question: "Quel taux de TVA pour un traiteur ?", reponse: "Le taux de 10 % s'applique aux prestations de traiteur avec consommation immédiate (livraison de plateaux-repas, buffets). Le taux de 5,5 % s'applique aux produits alimentaires vendus à emporter sans service. Le taux de 20 % concerne les boissons alcoolisées." },
      { question: "Un traiteur doit-il faire un devis ou une facture ?", reponse: "Un devis détaillé est obligatoire pour toute prestation événementielle. Après l'événement, une facture complète doit être émise avec les mentions légales, le détail des prestations réellement fournies et les éventuels suppléments." },
      { question: "Comment gérer les acomptes pour une prestation traiteur ?", reponse: "Il est courant de demander un acompte de 30 à 50 % à la commande. Émettez une facture d'acompte avec numéro séquentiel, puis une facture de solde après l'événement. La facture de solde doit déduire l'acompte déjà versé." },
      { question: "Quelles obligations Factur-X 2026 pour un traiteur ?", reponse: "Les traiteurs devront émettre des factures électroniques Factur-X pour leurs clients professionnels (entreprises, associations, collectivités) dès 2026. Les prestations aux particuliers feront l'objet du e-reporting." },
    ],
    ["fleuriste", "photographe", "coiffeur", "auto-entrepreneur"],
  ),
  metier("fleuriste", "Fleuriste", "artisanat",
    ["facture fleuriste", "logiciel caisse fleuriste"],
    ["Affichage des prix obligatoire", "TVA à 10% sur certaines plantes"],
    [
      { question: "Quel taux de TVA pour un fleuriste ?", reponse: "Le taux de TVA est de 10% pour les fleurs coupées, plantes vivantes et compositions florales. Le taux de 20% s'applique aux accessoires et contenants décoratifs." },
      { question: "Un fleuriste doit-il faire une facture ou une note ?", reponse: "Pour les particuliers, une note (ticket de caisse) suffit en dessous de 25 € TTC. Au-delà, une note détaillée est obligatoire. Pour les clients professionnels (entreprises, hôtels, événementiel), une facture complète est toujours requise." },
      { question: "Comment afficher les prix en boutique de fleurs ?", reponse: "L'affichage des prix TTC est obligatoire pour chaque produit proposé à la vente (arrêté du 3 décembre 1987). Pour les compositions sur mesure, affichez un prix indicatif au budget ou le prix à la tige pour les principales variétés." },
      { question: "Comment facturer des prestations de décoration florale événementielle ?", reponse: "Établissez un devis détaillant : les compositions (nombre, taille, variétés), la livraison, l'installation, le démontage éventuel et la location de vases/structures. Facturez un acompte de 30 à 50 % à la commande." },
      { question: "Quelles obligations Factur-X 2026 pour un fleuriste ?", reponse: "Les fleuristes devront émettre des factures électroniques Factur-X pour leurs clients professionnels (entreprises, collectivités, hôtels) dès 2026. Le e-reporting des ventes aux particuliers sera aussi requis." },
    ],
    ["traiteur", "coiffeur", "estheticienne", "auto-entrepreneur"],
  ),

  // ── Santé ──
  metier("osteopathe", "Ostéopathe", "sante",
    ["facture osteopathe", "note honoraires osteopathie"],
    ["Note d'honoraires obligatoire", "Franchise de TVA (art. 261-4-1° du CGI)", "Numéro ADELI ou RPPS"],
    [
      { question: "Un ostéopathe doit-il facturer la TVA ?", reponse: "Non, les actes d'ostéopathie sont exonérés de TVA en vertu de l'article 261-4-1° du CGI. La mention « TVA non applicable, art. 261-4-1° du CGI » doit figurer sur les notes d'honoraires." },
      { question: "Quelle différence entre note d'honoraires et facture pour un ostéopathe ?", reponse: "La note d'honoraires est le document émis par les professions libérales de santé. Elle contient les mêmes mentions obligatoires qu'une facture (identité, date, montant, numéro séquentiel) mais porte la dénomination « note d'honoraires »." },
      { question: "Un ostéopathe doit-il mentionner son numéro ADELI ou RPPS ?", reponse: "Oui, le numéro ADELI (ou RPPS selon l'enregistrement) doit figurer sur les notes d'honoraires. Ce numéro atteste de l'inscription au registre des professionnels de santé et permet le remboursement par les mutuelles." },
      { question: "Comment facturer un patient pour le remboursement par la mutuelle ?", reponse: "Émettez une note d'honoraires détaillée avec votre numéro ADELI/RPPS, la nature de l'acte (« consultation d'ostéopathie »), la date et le montant. La plupart des mutuelles exigent ce document pour rembourser leurs assurés." },
      { question: "La facturation électronique Factur-X concerne-t-elle les ostéopathes ?", reponse: "Pour les consultations de particuliers, le e-reporting sera requis dès 2026. Pour les prestations facturées à des entreprises (séances en entreprise, clubs sportifs), les notes d'honoraires devront être au format Factur-X." },
    ],
    ["kinesitherapeute", "dieteticien", "infirmier-liberal", "coach"],
  ),
  metier("kinesitherapeute", "Kinésithérapeute", "sante",
    ["facture kine", "note honoraires kinesitherapie"],
    ["Feuille de soins pour les actes remboursés", "Franchise de TVA", "Numéro RPPS obligatoire"],
    [
      { question: "Comment facturer en tant que kinésithérapeute libéral ?", reponse: "Pour les actes conventionnés, utilisez la feuille de soins (tiers payant ou remboursement patient). Pour les dépassements ou actes hors nomenclature, établissez une note d'honoraires séparée." },
      { question: "Un kinésithérapeute doit-il facturer la TVA ?", reponse: "Non, les actes de kinésithérapie sont exonérés de TVA en vertu de l'article 261-4-1° du CGI. Cette exonération couvre tous les actes thérapeutiques, y compris la rééducation et la balnéothérapie prescrites par un médecin." },
      { question: "Le numéro RPPS est-il obligatoire sur une note d'honoraires de kiné ?", reponse: "Oui, le numéro RPPS (Répertoire Partagé des Professionnels de Santé) doit figurer sur toutes les notes d'honoraires et feuilles de soins. Il remplace progressivement le numéro ADELI pour les kinésithérapeutes." },
      { question: "Comment facturer des séances de kiné en tiers payant ?", reponse: "En tiers payant, la part Sécurité sociale est facturée directement à la CPAM via le système Sesam-Vitale. Seul le reste à charge (ticket modérateur) est facturé au patient, sauf si la mutuelle pratique aussi le tiers payant complémentaire." },
      { question: "Un kiné peut-il facturer des actes hors nomenclature ?", reponse: "Oui, les actes hors nomenclature (kiné du sport, drainage esthétique, bien-être) sont facturés librement via une note d'honoraires. Ces actes ne sont pas remboursés par la Sécurité sociale mais peuvent l'être par certaines mutuelles." },
    ],
    ["osteopathe", "infirmier-liberal", "dieteticien", "formateur"],
  ),
  metier("infirmier-liberal", "Infirmier libéral", "sante",
    ["facture infirmier liberal", "facturation soins infirmiers"],
    ["Facturation Sesam-Vitale", "Franchise de TVA", "Numéro RPPS"],
    [
      { question: "Comment facturer les soins infirmiers à domicile ?", reponse: "Les soins infirmiers conventionnés sont facturés via le système Sesam-Vitale (tiers payant). Les majorations (nuit, dimanche, urgence, déplacement) sont codifiées. Les soins hors nomenclature sont facturés librement." },
      { question: "Les soins infirmiers sont-ils exonérés de TVA ?", reponse: "Oui, les actes de soins infirmiers sont exonérés de TVA en vertu de l'article 261-4-1° du CGI. Cette exonération s'applique à tous les actes thérapeutiques réalisés par un infirmier diplômé d'État, qu'ils soient conventionnés ou non." },
      { question: "Le numéro RPPS est-il obligatoire pour un infirmier libéral ?", reponse: "Oui, le numéro RPPS doit figurer sur toutes les feuilles de soins et notes d'honoraires. Il est indispensable pour la télétransmission Sesam-Vitale et l'identification auprès de la CPAM et des organismes complémentaires." },
      { question: "Comment facturer les indemnités de déplacement en soins infirmiers ?", reponse: "Les indemnités forfaitaires de déplacement (IFD) et les indemnités kilométriques (IK) sont codifiées par la convention nationale. Elles s'ajoutent automatiquement aux actes lors de la télétransmission via Sesam-Vitale." },
      { question: "Un infirmier libéral est-il concerné par Factur-X 2026 ?", reponse: "Pour les actes conventionnés aux particuliers, la facturation passe par Sesam-Vitale. En revanche, les prestations facturées à des entreprises (médecine du travail, EHPAD) devront être au format Factur-X dès 2026." },
    ],
    ["kinesitherapeute", "osteopathe", "dieteticien", "auto-entrepreneur"],
  ),
  metier("dieteticien", "Diététicien", "sante",
    ["facture dieteticien", "note honoraires nutrition"],
    ["Franchise de TVA pour les actes paramédicaux", "Numéro ADELI"],
    [
      { question: "Les consultations diététiques sont-elles soumises à la TVA ?", reponse: "Non, les consultations diététiques réalisées par un diététicien diplômé sont exonérées de TVA. Utilisez la mention « TVA non applicable, art. 261-4-1° du CGI »." },
      { question: "Un diététicien doit-il émettre une note d'honoraires ou une facture ?", reponse: "Le diététicien émet une note d'honoraires pour ses consultations individuelles. Ce document doit comporter les mentions légales classiques (identité, SIRET, date, numéro, montant) ainsi que le numéro ADELI du praticien." },
      { question: "Le numéro ADELI est-il obligatoire pour un diététicien ?", reponse: "Oui, tout diététicien doit être enregistré au fichier ADELI auprès de l'ARS. Ce numéro doit figurer sur les notes d'honoraires et permet aux patients de demander un remboursement auprès de leur mutuelle." },
      { question: "Les consultations diététiques sont-elles remboursées ?", reponse: "Les consultations diététiques ne sont pas remboursées par la Sécurité sociale (sauf dans le cadre du dispositif « Mon bilan diététique » pour les jeunes). Certaines mutuelles proposent un forfait annuel. La note d'honoraires est indispensable pour le remboursement." },
      { question: "La facturation Factur-X 2026 concerne-t-elle les diététiciens ?", reponse: "Pour les consultations aux particuliers, le e-reporting sera requis. Pour les prestations facturées à des entreprises ou établissements de santé (EHPAD, cliniques, cantines), les notes d'honoraires devront être au format Factur-X dès 2026." },
    ],
    ["osteopathe", "kinesitherapeute", "infirmier-liberal", "coach"],
  ),
]

export function getMetierBySlug(slug: string): Metier | undefined {
  return METIERS.find(m => m.slug === slug)
}
