import type { ExempleDevis } from "@/lib/pseo/guides"

export interface Modele {
  slug: string
  /** Titre affiché (h1). */
  titre: string
  /** Balise <title>, quand elle doit viser une autre formulation que le h1. */
  titreSeo?: string
  description: string
  motsCles: string[]
  type: "facture" | "devis" | "avoir" | "bon-de-commande" | "relance"
  pourQui: string
  contenu: string[]
  conseils: string[]
  mentionsSpecifiques: string[]
  /** Exemple chiffré affiché sous le modèle (totaux calculés par lib/pseo/exemple-devis.ts). */
  exemple?: ExempleDevis
}

export const MODELES: Modele[] = [
  {
    slug: "facture-auto-entrepreneur",
    titre: "Modèle de facture auto-entrepreneur gratuit",
    description: "Modèle de facture auto-entrepreneur (micro-entreprise) gratuit, avec les mentions obligatoires et la mention de franchise de TVA. Prêt à utiliser.",
    motsCles: ["modele facture auto entrepreneur", "facture micro entreprise gratuit", "exemple facture auto entrepreneur"],
    type: "facture",
    pourQui: "Auto-entrepreneurs et micro-entrepreneurs qui veulent facturer leurs clients dans le respect de la législation française.",
    contenu: [
      "Coordonnées complètes de l'auto-entrepreneur (nom, adresse, SIRET)",
      "Mention « EI » ou « Entrepreneur individuel »",
      "Coordonnées du client",
      "Numéro de facture chronologique",
      "Date d'émission",
      "Description détaillée des prestations",
      "Prix unitaire et montant total HT",
      "Mention « TVA non applicable, article 293 B du CGI »",
      "Conditions et délai de paiement",
      "Pénalités de retard et indemnité de recouvrement",
    ],
    conseils: [
      "Utilisez une numérotation continue et chronologique (ex : F-2026-001, F-2026-002)",
      "Conservez toutes vos factures pendant 10 ans",
      "Émettez la facture dès la fin de la prestation (une facture récapitulative par mois au plus tard en fin de mois)",
      "Surveillez vos seuils de franchise de TVA (en 2026 : 37 500 € pour les services, 85 000 € pour la vente)",
    ],
    mentionsSpecifiques: [
      "TVA non applicable, article 293 B du CGI",
      "Dispensé d'immatriculation au RCS et au RM (si applicable)",
    ],
  },
  {
    slug: "facture-classique",
    titre: "Modèle de facture classique gratuit",
    description: "Modèle de facture professionnelle gratuit avec toutes les mentions obligatoires. Pour les TPE, PME, artisans et indépendants.",
    motsCles: ["modele facture gratuit", "exemple facture", "modele facture professionnelle"],
    type: "facture",
    pourQui: "Toute entreprise ou tout professionnel indépendant qui veut émettre des factures conformes à la réglementation française.",
    contenu: [
      "Identité complète du vendeur (raison sociale, SIRET, TVA intracommunautaire, RCS)",
      "Identité et adresse du client",
      "Numéro de facture unique et séquentiel",
      "Date d'émission et date de la prestation",
      "Désignation détaillée des produits ou services",
      "Quantités, prix unitaires HT, taux de TVA",
      "Montant total HT, TVA et TTC",
      "Conditions de paiement et échéance",
      "Pénalités de retard et indemnité forfaitaire de 40 €",
    ],
    conseils: [
      "Vérifiez que toutes les mentions obligatoires sont présentes avant l'envoi",
      "Conservez un double de chaque facture pendant 10 ans",
      "En cas d'erreur, ne modifiez jamais une facture émise : émettez un avoir",
    ],
    mentionsSpecifiques: [],
  },
  {
    slug: "facture-acompte",
    titre: "Modèle de facture d'acompte gratuit",
    description: "Modèle de facture d'acompte gratuit, avec les mentions obligatoires, pour le BTP et les prestations payées en partie avant le début des travaux.",
    motsCles: ["modele facture acompte", "facture acompte gratuit", "exemple facture acompte"],
    type: "facture",
    pourQui: "Artisans, entreprises du BTP et prestataires de services qui demandent un acompte avant le début des travaux.",
    contenu: [
      "Toutes les mentions obligatoires d'une facture classique",
      "Référence du devis accepté",
      "Mention « Facture d'acompte »",
      "Montant total du devis ou de la commande",
      "Pourcentage et montant de l'acompte",
      "TVA calculée sur l'acompte",
      "Solde restant dû",
    ],
    conseils: [
      "L'acompte est généralement de 30 % à la commande dans le BTP",
      "La facture d'acompte fait partie de la numérotation séquentielle normale",
      "Émettez la facture de solde en fin de travaux en y référençant les acomptes versés",
    ],
    mentionsSpecifiques: [
      "Facture d'acompte",
      "Référence devis n° [X] du [date]",
    ],
  },
  {
    slug: "devis-travaux",
    titre: "Modèle de devis travaux gratuit pour artisan",
    titreSeo: "Modèle de devis artisan gratuit et exemple de devis travaux",
    description: "Modèle de devis artisan gratuit pour vos travaux : mentions obligatoires, matériaux et main-d'œuvre détaillés, TVA, et un exemple de devis chiffré.",
    motsCles: ["modele devis travaux", "modele devis artisan", "devis exemple", "exemple devis travaux", "devis matériaux", "devis travaux gratuit"],
    type: "devis",
    pourQui: "Artisans et entreprises du bâtiment qui veulent établir des devis détaillés et conformes pour leurs clients, particuliers ou professionnels.",
    contenu: [
      "Mention « Devis » en titre",
      "Date et durée de validité",
      "Coordonnées de l'entreprise (SIREN ou SIRET, « EI » pour un entrepreneur individuel)",
      "Coordonnées du client et adresse du chantier",
      "Description détaillée des travaux",
      "Détail des fournitures et des matériaux (quantité, unité, prix unitaire)",
      "Détail de la main-d'œuvre (heures ou mètres carrés, taux horaire TTC chez un particulier)",
      "Frais de déplacement, s'il y en a",
      "Évacuation des déchets du chantier : gestion, point de collecte et coût",
      "Taux de TVA de chaque ligne (5,5 %, 10 % ou 20 %)",
      "Montant total HT et TTC",
      "Conditions de paiement (acompte, échéances)",
      "Assurance décennale : assureur, n° de contrat, couverture géographique",
      "Emplacement pour la signature du client, précédée de « Bon pour accord »",
    ],
    conseils: [
      "Détaillez les postes ligne par ligne : fournitures, main-d'œuvre, déplacement, déchets",
      "Indiquez une durée de validité (un à trois mois est courant) : aucune durée n'est fixée par la loi",
      "Prévoyez qu'un travail supplémentaire se fera sur avenant signé",
      "Mentionnez la date ou le délai d'exécution, obligatoire chez un particulier",
      "Écrivez « acompte » pour la somme demandée à la signature : sans précision, celle d'un particulier est considérée comme des arrhes",
    ],
    mentionsSpecifiques: [
      "Bon pour accord, le [date] (mention du client avant sa signature)",
      "Assurance décennale : [Assureur], contrat n° [X], couverture : France métropolitaine",
      "Le client certifie que le logement est achevé depuis plus de deux ans et que les travaux ne sont pas exclus du taux réduit",
    ],
    exemple: {
      titre: "Pose de carrelage dans une salle de bains",
      contexte: "Exemple fictif : devis pour un particulier, dans une maison achevée depuis plus de deux ans, donc TVA à 10 %. Les prix illustrent la méthode ; ce ne sont pas des prix de marché.",
      lignes: [
        { designation: "Carrelage sol grès cérame 60 × 60 (référence, ou équivalent), fourni, chutes comprises", quantite: 13, unite: "m²", prixUnitaireHT: 32 },
        { designation: "Mortier-colle, joints et profilés de finition", quantite: 1, unite: "forfait", prixUnitaireHT: 85 },
        { designation: "Dépose de l'ancien carrelage", quantite: 12, unite: "m²", prixUnitaireHT: 15 },
        { designation: "Préparation du support : ragréage", quantite: 12, unite: "m²", prixUnitaireHT: 12 },
        { designation: "Pose du carrelage et des joints", quantite: 12, unite: "m²", prixUnitaireHT: 42 },
        { designation: "Évacuation des gravats et dépôt en déchèterie professionnelle", quantite: 1, unite: "forfait", prixUnitaireHT: 60 },
      ],
      tauxTva: 10,
      acomptePourcent: 30,
      conditions: [
        "Devis gratuit, valable deux mois.",
        "Travaux réalisés en trois jours, dans les 30 jours qui suivent la signature.",
        "Taux horaire pour un travail supplémentaire accepté par avenant : 50,00 € HT, soit 55,00 € TTC.",
        "Déchets : environ 0,5 m³ de gravats, triés et déposés en déchèterie professionnelle (nom et adresse à indiquer), coût compris dans la ligne d'évacuation.",
        "Acompte de 30 % à la signature, solde à la fin des travaux. Signé au domicile du client, l'acompte ne pourrait être encaissé qu'au bout de sept jours.",
        "Le client certifie que le logement est achevé depuis plus de deux ans et que les travaux ne sont pas exclus du taux réduit.",
        "Signature du client précédée de « Bon pour accord ».",
      ],
    },
  },
  {
    slug: "devis-prestation-service",
    titre: "Modèle de devis prestation de service gratuit",
    description: "Modèle de devis pour prestation de service gratuit. Idéal pour les consultants, freelances, formateurs et prestataires intellectuels.",
    motsCles: ["modele devis prestation service", "devis freelance", "devis consultant gratuit"],
    type: "devis",
    pourQui: "Freelances, consultants, formateurs et prestataires de services intellectuels qui veulent formaliser leurs propositions commerciales.",
    contenu: [
      "Mention « Devis » ou « Proposition commerciale »",
      "Date et durée de validité",
      "Coordonnées du prestataire",
      "Coordonnées du client",
      "Description détaillée de la mission",
      "Livrables attendus",
      "Planning et jalons",
      "Tarification (forfait, taux journalier, taux horaire)",
      "Conditions de révision de prix",
      "Conditions de paiement",
      "Clause de confidentialité",
      "Conditions d'annulation",
    ],
    conseils: [
      "Définissez clairement le périmètre de la mission pour éviter les dérives",
      "Indiquez le nombre de révisions incluses dans le forfait",
      "Prévoyez une clause pour les demandes supplémentaires (avenant)",
    ],
    mentionsSpecifiques: [],
  },
  {
    slug: "avoir-annulation",
    titre: "Modèle d'avoir (note de crédit) gratuit",
    description: "Modèle d'avoir gratuit pour annuler ou corriger une facture : mentions obligatoires, référence de la facture d'origine, TVA.",
    motsCles: ["modele avoir", "note de credit modele", "annuler une facture modele"],
    type: "avoir",
    pourQui: "Toute entreprise qui doit annuler ou corriger une facture déjà émise (erreur, retour, remise).",
    contenu: [
      "Mention « Avoir » ou « Note de crédit »",
      "Numéro d'avoir (dans la séquence de facturation)",
      "Date d'émission",
      "Référence de la facture d'origine (numéro et date)",
      "Motif de l'avoir (retour, erreur, remise, annulation)",
      "Détail des montants crédités (HT, TVA, TTC)",
      "Montants en négatif",
      "Mode de remboursement ou report",
    ],
    conseils: [
      "Ne supprimez jamais une facture : émettez toujours un avoir",
      "L'avoir suit la même numérotation séquentielle que les factures",
      "Conservez l'avoir et la facture d'origine ensemble pendant 10 ans",
    ],
    mentionsSpecifiques: [
      "Avoir sur facture n° [X] du [date]",
      "Motif : [retour de marchandise / erreur / remise commerciale / annulation]",
    ],
  },
  {
    slug: "bon-de-commande",
    titre: "Modèle de bon de commande gratuit",
    description: "Modèle de bon de commande gratuit et professionnel, pour formaliser les commandes de fournitures, de matériaux ou de prestations.",
    motsCles: ["modele bon de commande", "bon de commande gratuit", "exemple bon de commande"],
    type: "bon-de-commande",
    pourQui: "Entreprises et artisans qui veulent formaliser leurs commandes auprès de fournisseurs ou confirmer une commande client.",
    contenu: [
      "Mention « Bon de commande »",
      "Numéro de bon de commande",
      "Date et référence",
      "Coordonnées de l'émetteur et du fournisseur",
      "Description des articles ou services commandés",
      "Quantités et prix unitaires",
      "Conditions de livraison (délai, lieu, transport)",
      "Conditions de paiement",
      "Signature de validation",
    ],
    conseils: [
      "Numérotez vos bons de commande pour faciliter le suivi",
      "Reliez chaque bon de commande au devis correspondant",
      "Vérifiez les conditions de livraison et les délais avant validation",
    ],
    mentionsSpecifiques: [],
  },
  {
    slug: "facture-proforma",
    titre: "Modèle de facture proforma gratuit",
    description: "Modèle de facture proforma gratuit : document commercial de préfacturation pour les devis internationaux et les formalités douanières.",
    motsCles: ["facture proforma modele", "proforma gratuit", "facture proforma exemple"],
    type: "facture",
    pourQui: "Entreprises qui réalisent des opérations à l'international ou qui veulent émettre un document de préfacturation sans valeur comptable.",
    contenu: [
      "Mention « Facture proforma » (bien visible)",
      "Mention « Ce document n'est pas une facture »",
      "Coordonnées de l'émetteur et du destinataire",
      "Description des biens ou des services",
      "Quantités, prix unitaires, montant total",
      "Incoterms (pour l'international)",
      "Devise et taux de change",
      "Conditions de paiement",
      "Durée de validité",
    ],
    conseils: [
      "La facture proforma n'a aucune valeur comptable ni fiscale",
      "Elle ne doit pas porter de numéro de facture (elle n'entre pas dans la numérotation)",
      "Émettez une vraie facture une fois la commande confirmée",
    ],
    mentionsSpecifiques: [
      "PROFORMA — Ce document n'est pas une facture et n'a pas de valeur comptable",
    ],
  },
  {
    slug: "facture-situation",
    titre: "Modèle de facture de situation (BTP) gratuit",
    description: "Modèle de facture de situation gratuit pour le BTP : facturation à l'avancement du chantier, cumul des situations précédentes et solde.",
    motsCles: ["facture de situation", "facture avancement travaux", "facture situation BTP gratuit"],
    type: "facture",
    pourQui: "Entreprises du bâtiment qui facturent par tranches selon l'avancement des travaux (gros œuvre, second œuvre, finitions).",
    contenu: [
      "Mention « Facture de situation n° [X] »",
      "Référence du marché ou du devis accepté",
      "Tableau d'avancement par poste (% réalisé)",
      "Montant cumulé des situations précédentes",
      "Montant de la situation en cours",
      "Retenue de garantie (5 % au maximum, art. L. 111-10-1 du CCH)",
      "TVA calculée sur la situation",
      "Solde restant à facturer",
      "Toutes les mentions obligatoires d'une facture classique",
    ],
    conseils: [
      "Faites valider le pourcentage d'avancement par le maître d'ouvrage ou le maître d'œuvre avant d'émettre la facture",
      "Numérotez les situations dans l'ordre (situation 1, 2, 3…)",
      "La retenue de garantie de 5 % est libérée un an après la réception des travaux",
      "Conservez le tableau d'avancement signé avec chaque facture",
    ],
    mentionsSpecifiques: [
      "Situation n° [X] sur [Y] — Avancement global : [Z] %",
      "Retenue de garantie de 5 % conformément à l'article L. 111-10-1 du CCH",
    ],
  },
  {
    slug: "facture-recurrente",
    titre: "Modèle de facture récurrente gratuit",
    description: "Modèle de facture récurrente gratuit pour les abonnements et prestations mensuelles : période couverte, référence du contrat, numérotation continue.",
    motsCles: ["facture recurrente", "facture abonnement", "facture mensuelle modele gratuit"],
    type: "facture",
    pourQui: "Prestataires de services qui facturent de manière périodique : maintenance, abonnements, locations, contrats mensuels.",
    contenu: [
      "Toutes les mentions obligatoires d'une facture classique",
      "Mention de la périodicité (mensuelle, trimestrielle, annuelle)",
      "Référence du contrat ou de l'abonnement",
      "Période couverte (du [date] au [date])",
      "Montant fixe ou variable selon la consommation",
      "Conditions de résiliation",
      "Date de prélèvement ou échéance",
      "Numéro de facture unique et séquentiel (même pour les factures récurrentes)",
    ],
    conseils: [
      "Chaque facture récurrente doit avoir un numéro unique dans votre séquence chronologique",
      "Mentionnez clairement la période couverte pour éviter les contestations",
      "Émettez vos factures à date fixe chaque période : votre client sait quand payer",
      "Prévoyez une clause de révision de prix dans le contrat",
    ],
    mentionsSpecifiques: [
      "Facture périodique — Contrat n° [X]",
      "Période : du [date de début] au [date de fin]",
    ],
  },
  {
    slug: "lettre-relance-impaye",
    titre: "Modèle de lettre de relance pour facture impayée",
    description: "Modèle gratuit de lettre de relance pour facture impayée, en 3 niveaux : relance amiable, relance ferme, mise en demeure.",
    motsCles: ["lettre relance facture impayee", "relance impaye modele", "modele mise en demeure facture"],
    type: "relance",
    pourQui: "Toute entreprise confrontée à des retards de paiement qui veut relancer ses clients de manière professionnelle.",
    contenu: [
      "En-tête avec les coordonnées de l'entreprise",
      "Coordonnées du débiteur",
      "Référence de la ou des factures impayées (numéro, date, montant)",
      "Date d'échéance dépassée",
      "Montant dû et pénalités de retard calculées",
      "Indemnité forfaitaire de recouvrement de 40 €",
      "Délai accordé pour le règlement (8 à 15 jours)",
      "Mention des suites en cas de non-paiement",
      "Trois niveaux progressifs : relance amiable, relance ferme, mise en demeure en LRAR",
    ],
    conseils: [
      "Envoyez la première relance 7 jours après l'échéance (un email suffit)",
      "La deuxième relance (15 jours) doit être plus ferme et mentionner les pénalités",
      "La mise en demeure en LRAR est un préalable nécessaire à l'action en justice",
      "Conservez une copie de toutes les relances envoyées comme preuve",
    ],
    mentionsSpecifiques: [
      "Pénalités de retard : taux de [X] % (minimum 3 fois le taux d'intérêt légal)",
      "Indemnité forfaitaire de recouvrement : 40 € (article D441-5 du Code de commerce)",
    ],
  },
]

export function getModeleBySlug(slug: string): Modele | undefined {
  return MODELES.find(m => m.slug === slug)
}
